#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.QTBHXH
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QTBHXH/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<HRM.QLBHXH.Models.nvbhQuaTrinhBHXH>
    {
        public Create()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\QTBHXH\Create.cshtml"
  
    ViewBag.Title = "Create";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Create</h2>\r\n\r\n");

            
            #line 9 "..\..\Views\QTBHXH\Create.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\QTBHXH\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\QTBHXH\Create.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>nvbhQuaTrinhBHXH</legend>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.idNVBHXH, "nvbhNhanVienBHXH"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.DropDownList("idNVBHXH", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.idNVBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.ThoiGianKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.ThoiGianKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.ThoiGianKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 40 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.MucLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.MucLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.MucLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 48 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.MucDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.MucDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.MucDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.MucDongBHTN));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 59 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.MucDongBHTN));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 60 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.MucDongBHTN));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 64 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.HeSoTienLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 67 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.HeSoTienLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 68 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.HeSoTienLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 72 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.MucDongToiThieu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 75 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.MucDongToiThieu));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 76 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.MucDongToiThieu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 80 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.GhiChu1));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 83 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.GhiChu1));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 84 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.GhiChu1));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 88 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.LabelFor(model => model.GhiChu2));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 91 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.EditorFor(model => model.GhiChu2));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 92 "..\..\Views\QTBHXH\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.GhiChu2));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <p>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Create\"");

WriteLiteral(" />\r\n        </p>\r\n    </fieldset>\r\n");

            
            #line 99 "..\..\Views\QTBHXH\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 102 "..\..\Views\QTBHXH\Create.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
