#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.QTBHXH
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QTBHXH/Index2.cshtml")]
    public partial class Index2 : System.Web.Mvc.WebViewPage<IEnumerable<HRM.QLBHXH.Models.v_qtbhxh>>
    {
        public Index2()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\QTBHXH\Index2.cshtml"
  
    ViewBag.Title = "Index2";
    var ten = ViewBag.Ten1;
    var idqt = @ViewBag.idqt;
    //var idqt = ViewBag.idqt;
    var tongnambhxh = ViewBag.tongnambhxh;
    var tongthangbhxh = ViewBag.tongthangbhxh;
    var tongnambhtn = ViewBag.tongnambhtn;
    var tongthangbhtn = ViewBag.tongthangbhtn;


            
            #line default
            #line hidden


WriteLiteral(" <a style=\"text-align: right\" title=\"Trở lại danh sách NV BHXH\" onclick=\"location" +
".href=\'");


            
            #line 14 "..\..\Views\QTBHXH\Index2.cshtml"
                                                                                     Write(Url.Action("index2", "NhanVienBHXH"));

            
            #line default
            #line hidden
WriteLiteral("\'\">\r\n    <span class=\"ui-icon     \r\nui-icon-arrowreturnthick-1-w \" style=\"display" +
": inline-block\" /></a>\r\n");


            
            #line 17 "..\..\Views\QTBHXH\Index2.cshtml"
 if (idqt != -1)
{

            
            #line default
            #line hidden
WriteLiteral("    <font size=\"3\" color=\"#0099CC\"><b>Quá trình tham gian BHXH của ");


            
            #line 19 "..\..\Views\QTBHXH\Index2.cshtml"
                                                              Write(ten);

            
            #line default
            #line hidden
WriteLiteral("</b></font> \r\n");


            
            #line 20 "..\..\Views\QTBHXH\Index2.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"<a
        style=""text-align: right"" title=""Đóng"" class='button2'><span class=""ui-icon ui-icon-closethick""
            style=""display: inline-block"" /> </a>
<div id=""tgbh"" style=""background: #FFFFCC"">
    <div>
        <b>Tổng thời gian tham gia BHXH: </b>
");


            
            #line 27 "..\..\Views\QTBHXH\Index2.cshtml"
         if (tongnambhxh != null)
            {
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\QTBHXH\Index2.cshtml"
        Write(tongnambhxh);

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\QTBHXH\Index2.cshtml"
                         }
        else
            {
            
            #line default
            #line hidden
WriteLiteral(" <span>0</span>");


            
            #line 30 "..\..\Views\QTBHXH\Index2.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("        năm,\r\n");


            
            #line 32 "..\..\Views\QTBHXH\Index2.cshtml"
         if (tongthangbhxh != null)
             {
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\QTBHXH\Index2.cshtml"
         Write(tongthangbhxh);

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\QTBHXH\Index2.cshtml"
                            }
             else
             {
            
            #line default
            #line hidden
WriteLiteral(" <span>0</span>");


            
            #line 35 "..\..\Views\QTBHXH\Index2.cshtml"
                             }

            
            #line default
            #line hidden
WriteLiteral("        tháng</div>\r\n    <div>\r\n        <b>Tổng thời gian tham gia BHTH: </b>\r\n");


            
            #line 39 "..\..\Views\QTBHXH\Index2.cshtml"
         if (tongnambhtn != null)
          {
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\QTBHXH\Index2.cshtml"
       Write(tongnambhtn);

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\QTBHXH\Index2.cshtml"
                        
            }
        else
             {
            
            #line default
            #line hidden
WriteLiteral(" <span>0</span>");


            
            #line 44 "..\..\Views\QTBHXH\Index2.cshtml"
                             }

            
            #line default
            #line hidden
WriteLiteral("        năm,\r\n");


            
            #line 46 "..\..\Views\QTBHXH\Index2.cshtml"
         if (tongthangbhtn != null)
             {
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\QTBHXH\Index2.cshtml"
         Write(tongthangbhtn);

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\QTBHXH\Index2.cshtml"
                             }
             else
             {
            
            #line default
            #line hidden
WriteLiteral(" <span>0</span>");


            
            #line 49 "..\..\Views\QTBHXH\Index2.cshtml"
                             }

            
            #line default
            #line hidden
WriteLiteral(@"        tháng</div>
</div>
<div id=""delete"">
   <div align=""center"">
        
        <img src=""/../../Forms/HRM1/Images/bar-large-green.gif"" id=""imgProg1"" visible=""false"" /></div>
    <p id=""imgProg1"" visible=""false"" align=""center"">
        ĐANG TẢI...</p>

</div>
<table id=""QuaTrinh"">
    <thead>
        <tr>
            <th style=""text-align: center"" nowrap rowspan=""2"">
                Mã NV
            </th>
            <th style=""text-align: center"" nowrap rowspan=""2"">
                Họ và tên
            </th>
            <th style=""text-align: center"" nowrap rowspan=""2"">
                Đơn vị
            </th>
            <th style=""text-align: center"" rowspan=""2"" nowrap>
                Số sổ BHXH
            </th>
            <th style=""text-align: center"" nowrap rowspan=""2"">
                Số phiếu KCB
            </th>
            ");



WriteLiteral(@"
            <th style=""text-align: center; border-right: 1.5px solid gray;"" nowrap colspan=""5"">
                QÚA TRÌNH THAM GIA BHXH (Ghi sổ)
            </th>
            <th style=""text-align: center; border-right: 1.5px solid gray;"" nowrap colspan=""5"">
                Theo dõi
            </th>
            <th style=""text-align: center"" nowrap rowspan=""2"">
                Ghi chú 1
            </th>
            ");



WriteLiteral(@"
            <th rowspan=""2"">
            </th>
        </tr>
        <tr>
            <th style=""text-align: left"" nowrap>
                TG bắt đầu
            </th>
            <th style=""text-align: left"" nowrap>
                TG kết thúc
            </th>
            ");



WriteLiteral(@"
            <th style=""text-align: left"" nowrap>
                ML đóng BHXH
            </th>
              <th style=""text-align: left"" nowrap>
                Mức đóng BHXH
            </th>
              <th style=""text-align: left"" nowrap>
                Mức đóng BHXH
            </th>

            <th style=""text-align: left"" nowrap>
                TL BHXH
            </th>
            <th style=""text-align: left"" nowrap>
                TL BHYT
            </th>
            <th style=""text-align: left"" nowrap>
                TL BHTN
            </th>
            <th style=""text-align: left"" nowrap>
                MLTTC
            </th>
            <th style=""text-align: left"" nowrap>
                MLTTV
            </th>
        </tr>
    </thead>
    <tbody>
");


            
            #line 140 "..\..\Views\QTBHXH\Index2.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td style=\"text-align: left\" nowrap>\r\n         " +
"           ");


            
            #line 144 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(Html.DisplayFor(modelItem => item.MANV));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 147 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(Html.DisplayFor(modelItem => item.HoVaTen));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 150 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(Html.DisplayFor(modelItem => item.DonVi));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 153 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(Html.DisplayFor(modelItem => item.SoBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 156 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(Html.DisplayFor(modelItem => item.SoKCB));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n");


            
            #line 159 "..\..\Views\QTBHXH\Index2.cshtml"
                     if (item.ThoiGianBatDau != null)
                    {
                        
            
            #line default
            #line hidden
            
            #line 161 "..\..\Views\QTBHXH\Index2.cshtml"
                   Write(item.ThoiGianBatDau.Value.ToString("MM/yyyy"));

            
            #line default
            #line hidden
            
            #line 161 "..\..\Views\QTBHXH\Index2.cshtml"
                                                                      }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n");


            
            #line 164 "..\..\Views\QTBHXH\Index2.cshtml"
                     if (item.ThoiGianKetThuc != null)
                    {
                        
            
            #line default
            #line hidden
            
            #line 166 "..\..\Views\QTBHXH\Index2.cshtml"
                   Write(item.ThoiGianKetThuc.Value.ToString("MM/yyyy"));

            
            #line default
            #line hidden
            
            #line 166 "..\..\Views\QTBHXH\Index2.cshtml"
                                                                       }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n    " +
"                ");


            
            #line 169 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.MucLuongDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                 <td style=\"text-align: left\" nowrap>\r\n " +
"                   ");


            
            #line 172 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.MucDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                 <td style=\"text-align: left\" nowrap>\r\n " +
"                   ");


            
            #line 175 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.MucDongBHTN));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 178 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.TLBHXH));

            
            #line default
            #line hidden
WriteLiteral("%\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n " +
"                   ");


            
            #line 181 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.TLBHYT));

            
            #line default
            #line hidden
WriteLiteral("%\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n " +
"                   ");


            
            #line 184 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.TLBHTN));

            
            #line default
            #line hidden
WriteLiteral("%\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n " +
"                   ");


            
            #line 187 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.MLTTC));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 190 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(String.Format("{0:#,##0}", item.MLTTV));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td style=\"text-align: left\" nowrap>\r\n  " +
"                  ");


            
            #line 193 "..\..\Views\QTBHXH\Index2.cshtml"
               Write(Html.DisplayFor(modelItem => item.GhiChu1));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                ");



WriteLiteral("\r\n                <td style=\"text-align: left\" nowrap>\r\n                    <a da" +
"ta-val1=\"");


            
            #line 199 "..\..\Views\QTBHXH\Index2.cshtml"
                             Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Xóa\" class=\'button1\'><span class=\"ui-icon ui-icon-trash\"\r\n              " +
"          style=\"display: inline-block\" /></a>\r\n                </td>\r\n         " +
"   </tr>\r\n");


            
            #line 203 "..\..\Views\QTBHXH\Index2.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n<script src=\"/Scripts/datatables/FixedColumns.js\"></scrip" +
"t>\r\n<script src=\"/Content/datatables/DataTableFixedHeader.js\"></script>\r\n<script" +
">\r\n\r\n//    $(\'#tgbh\').show();\r\n    $(window).load(function () {\r\n    if(");


            
            #line 212 "..\..\Views\QTBHXH\Index2.cshtml"
  Write(idqt);

            
            #line default
            #line hidden
WriteLiteral("!=-1){\r\n\r\n\r\n        $(\"#tgbh\").slideDown();\r\n        }\r\n    });\r\n    $.get(\"../QT" +
"BHXH/delete?id=1\").success(function (data) {\r\n        $(\'#delete\').html(data);\r\n" +
"     \r\n    });\r\n    $(\"#delete\").tabs();\r\n\r\n \r\n\r\n    $(\".button2\").hide();\r\n    " +
"var oTable = $(\'#QuaTrinh\').dataTable({\r\n        \"bJQueryUI\": true,\r\n        \"sS" +
"crollY\": \"100%\",\r\n        \"sScrollX\": \"100%\"\r\n        , \"bSort\": false\r\n\r\n\r\n    " +
"});\r\n    new $.fn.dataTable.FixedColumns(oTable, {\r\n        //        \"iLeftColu" +
"mns\": 2,\r\n        \"iRightColumns\": 1\r\n    });\r\n\r\n    //xu li nut xoa\r\n    $(func" +
"tion () {\r\n        $(\'.button1\').click(function () {\r\n            var Val1 = $(t" +
"his).attr(\"data-val1\");\r\n              $(\"#imgProg\").show();\r\n\r\n            $.ge" +
"t(\"../QTBHXH/delete?id=\" + Val1).success(function (data) {\r\n                $(\'#" +
"delete\').html(data);\r\n            \r\n                $(\"#delete\").slideDown(\"medi" +
"um\");\r\n                      $(\"#imgProg\").hide();\r\n\r\n            });\r\n         " +
"   var $t1 = $(\'#tgbh\');\r\n            if ($t1.is(\':visible\')) {\r\n               " +
" $t1.slideUp();\r\n                // Other stuff to do on slideUp\r\n            }\r" +
"\n             $(\'html, body\').animate({ scrollTop: 0 }, \'slow\');\r\n            $(" +
"\".button2\").show();\r\n        });\r\n    });\r\n\r\n    $(function () {\r\n        $(\'.bu" +
"tton2\').click(function () {\r\n            $(\".button2\").hide();\r\n            $(\"#" +
"delete\").slideUp(\"medium\");\r\n            if (idqt != -1)\r\n            {\r\n       " +
"         $(\'#tgbh\').slideDown();\r\n            }\r\n\r\n        });\r\n    });\r\n\r\n\r\n   " +
"  \r\n    \r\n//      //xu li nut loc\r\n//       $(function () {\r\n//        $(\"#btnLo" +
"c\").click(function () {\r\n//          var txtVal = $(\"#txt1\").val();\r\n//         " +
"   window.location = \"");


            
            #line 282 "..\..\Views\QTBHXH\Index2.cshtml"
                            Write(Url.Action("Index2", "QTBHXH"));

            
            #line default
            #line hidden
WriteLiteral(@""" +""?id="" + txtVal;
//        });
//        });


 

</script>
<style type=""text/css"">
    #delete,#tgbh
    {
        display: none;
    }
    
        .dataTables_wrapper tbody tr:hover {
    background-color: #FFFF00!important;
    cursor: pointer;
    * cursor: hand;
    
}
</style>
");


        }
    }
}
#pragma warning restore 1591
