#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLVayMuon.Views.ImportHoanVay
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ImportHoanVay\Index.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ImportHoanVay/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<HRM.QLVayMuon.Models.HoanVay>>
    {
        public Index()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


            
            #line 4 "..\..\Views\ImportHoanVay\Index.cshtml"
  
    ViewBag.Title = "Import";
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 9 "..\..\Views\ImportHoanVay\Index.cshtml"
Write(Html.ActionLink("Trở về danh sách nhân viên vay mượn", "Index", "NhanVienVayMuon"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 11 "..\..\Views\ImportHoanVay\Index.cshtml"
Write(Html.StatusMessage(TempData["Message_import"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 12 "..\..\Views\ImportHoanVay\Index.cshtml"
Write(Html.ValidationSummary(TempData["ModelState"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3 align=\"center\"><font>Tải Tệp Tin Excel Để Kiểm Tra</font></h3>\r\n");


            
            #line 14 "..\..\Views\ImportHoanVay\Index.cshtml"
  using (Html.BeginForm("Review", "ImportHoanVay", FormMethod.Post, new { enctype = "multipart/form-data" }))
 {

            
            #line default
            #line hidden
WriteLiteral(" <table align =center >\r\n <tr><td><input  type=\"file\"  id=\"FileUpload1\" name=\"Fil" +
"eUpload1\"/></td>\r\n <td><input  type=\"submit\" id=\"Submit\" name=\"Submit\" value=\"Tả" +
"i lên\"/></td>\r\n </tr>\r\n </table>\r\n");


            
            #line 21 "..\..\Views\ImportHoanVay\Index.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3 align=center>Danh sách hoàn vay</h3>\r\n\r\n");


            
            #line 25 "..\..\Views\ImportHoanVay\Index.cshtml"
Write(Html.StatusMessage(TempData["Message"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 26 "..\..\Views\ImportHoanVay\Index.cshtml"
Write(Html.ValidationSummary(TempData["ModelState"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n<table id = \"HoanVay\">\r\n<thead>\r\n    <tr>\r\n        <th>\r\n            ");


            
            #line 31 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Mã NV"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n            ");


            
            #line 34 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Họ và Tên"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n            ");


            
            #line 37 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Số chứng từ hoàn"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n            ");


            
            #line 40 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Ngày chứng từ"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n            ");


            
            #line 43 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Diễn giải"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n            ");


            
            #line 46 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Số tiền hoàn"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n            ");


            
            #line 49 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.VN("Số tiền lãi"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n        \r\n    </tr>\r\n   </thead>\r\n   <tbody>\r" +
"\n");


            
            #line 56 "..\..\Views\ImportHoanVay\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            ");


            
            #line 59 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.KhoanVay.NhanVienVayMuon.MaNV));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 62 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.KhoanVay.NhanVienVayMuon.HoVaTen));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 65 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.SoChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 68 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(item.NgayChungTu.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 71 "..\..\Views\ImportHoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.DienGiai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n              ");


            
            #line 74 "..\..\Views\ImportHoanVay\Index.cshtml"
         Write(String.Format("{0:#,##0}", item.SoTienHoan));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n               ");


            
            #line 77 "..\..\Views\ImportHoanVay\Index.cshtml"
          Write(String.Format("{0:#,##0}", item.SoTienLai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n         <td align=\"right\">\r\n            <a class=\"dialog\" href=" +
"\"/QLVayMuon/ImportHoanVay/Delete?id=");


            
            #line 80 "..\..\Views\ImportHoanVay\Index.cshtml"
                                                                  Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Xóa\"><span class=\"ui-icon ui-icon-trash\" style=\"display:inline-block\"/><" +
"/a>          \r\n        </td>\r\n    </tr>\r\n");


            
            #line 83 "..\..\Views\ImportHoanVay\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"</tbody>
</table>


<script>
    $(document).ready(function () {
        $(""#HoanVay"").dataTable({
            ""bAutoWidth"": true,
            ""bStateSave"": true,
            ""aLengthMenu"": [[10, 25, 50, -1], [10, 25, 50, ""All""]]
        });
    });
</script>
");


        }
    }
}
#pragma warning restore 1591
