#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.DSLaiTruyThuBH
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DSLaiTruyThuBH/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.QLBHXH.Models.nvbhLaiTruyThuBH>
    {
        public Edit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
  
    ViewBag.Title = "Edit";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");


            
            #line 9 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>nvbhLaiTruyThuBH</legend>\r\n\r\n        <span>\r\n    " +
"    ");


            
            #line 16 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Họ và tên: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 17 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.DropDownList("idnvbhNhanVienBHXH", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 18 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.idnvbhNhanVienBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <span>\r\n        ");


            
            #line 22 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Tiền lương hoặc chênh lệch tiền lương: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 23 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.EditorFor(model => model.TienLuongHoacChenhLechTienLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 24 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.TienLuongHoacChenhLechTienLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <span>\r\n        ");


            
            #line 27 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Từ tháng năm: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 28 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.EditorFor(model => model.TuThangNam));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 29 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.TuThangNam));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        ");


            
            #line 31 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Đến tháng năm: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 32 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.EditorFor(model => model.DenThangNam));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 33 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.DenThangNam));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        \r\n        ");


            
            #line 36 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Số tháng truy thu: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 37 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.EditorFor(model => model.SoThangTruyThu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 38 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.SoThangTruyThu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <span>\r\n        ");


            
            #line 41 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Năm áp dụng tỷ lệ đóng bảo hiểm: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 42 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.DropDownList("iddmTyLeDongBHXH", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 43 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.iddmTyLeDongBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <span>\r\n        ");


            
            #line 46 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Năm áp dụng Mức lương tối thiểu chung: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 47 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.DropDownList("iddmMucLuongToiThieuChung", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 48 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.iddmMucLuongToiThieuChung));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <span>\r\n        ");


            
            #line 51 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Năm áp dụng Lãi suất truy thu: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 52 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.DropDownList("iddmLaiSuatTruyThu", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 53 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.iddmLaiSuatTruyThu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <span>\r\n        ");


            
            #line 56 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Tổng thời gian chậm đóng: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 57 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.EditorFor(model => model.TongThoiGianChamDong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 58 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.TongThoiGianChamDong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <span>\r\n        ");


            
            #line 62 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.VN("Ghi chú: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 63 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.EditorFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 64 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n\r\n        <p>\r\n            <input type=\"submit\" value=\"Lưu\" />" +
"\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 71 "..\..\Views\DSLaiTruyThuBH\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<script>\r\n    $(\"#idnvbhNhanVienBHXH\").combobox();\r\n    $(\"#TuThangNam\").da" +
"tepicker({\r\n        changeDay: true,\r\n        changeMonth: true,\r\n        change" +
"Year: true\r\n    });\r\n</script>\r\n\r\n");



WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
