#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Webpages.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("featured", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"featured\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 106), Tuple.Create("\"", 131)
, Tuple.Create(Tuple.Create("", 112), Tuple.Create<System.Object, System.Int32>(Href("~/Images/Header.png")
, 112), false)
);

WriteLiteral(" />\r\n    </section>\r\n");

});

WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Home\Index.cshtml"
 if (String.IsNullOrEmpty(User.Identity.Name))
{
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\Index.cshtml"
Write(Html.Action("Index", "Login", new { area = "Account", partial = true }));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\Index.cshtml"
                                                                            
    return;
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n.main-content\r\n{\r\n    background-color: rgb(98, 111, 180);\r\n}\r\n    .myul  \r\n  " +
"  {\r\n        clear:both;\r\n        list-style-type:none;\r\n        margin-bottom: " +
"10px;\r\n    }\r\n.myul li\r\n{\r\n    float:left;\r\n    height: 180px;\r\n    width: 180px" +
";\r\n    margin: 10px;\r\n}\r\n.myul li img\r\n{\r\n    height: 100%;\r\n    width: 100%;\r\n}" +
"\r\nul.enlarge{\r\n    list-style-type:none; /*remove the bullet point*/\r\n    margin" +
"-left:0;\r\n    }\r\n    ul.enlarge li{\r\n    display:inline-block; /*places the imag" +
"es in a line*/\r\n    position: relative;\r\n    z-index: 0; /*resets the stack orde" +
"r of the list items - later we\'ll increase this*/\r\n    margin:10px 40px 0 20px;\r" +
"\n    }\r\nul.enlarge img{\r\n    background-color:#eae9d4;\r\n    padding: 6px;\r\n    -" +
"webkit-box-shadow: 0 0 6px rgba(132, 132, 132, .75);\r\n    -moz-box-shadow: 0 0 6" +
"px rgba(132, 132, 132, .75);\r\n    box-shadow: 0 0 6px rgba(132, 132, 132, .75);\r" +
"\n    -webkit-border-radius: 4px; \r\n    -moz-border-radius: 4px; \r\n    border-rad" +
"ius: 4px; \r\n}\r\nul.enlarge span{\r\n    position:absolute;\r\n    left: -9999px;\r\n   " +
" background-color:#eae9d4;\r\n    padding: 10px;\r\n    font-family: \'Droid Sans\', s" +
"ans-serif;\r\n    font-size:.9em;\r\n    text-align: center; \r\n    color: #495a62; \r" +
"\n    -webkit-box-shadow: 0 0 20px rgba(0,0,0, .75));\r\n    -moz-box-shadow: 0 0 2" +
"0px rgba(0,0,0, .75);\r\n    box-shadow: 0 0 20px rgba(0,0,0, .75);\r\n    -webkit-b" +
"order-radius: 8px; \r\n    -moz-border-radius: 8px; \r\n    border-radius:8px;\r\n}\r\nu" +
"l.enlarge li:hover{\r\n    z-index: 50;\r\n    cursor:pointer;\r\n}\r\nul.enlarge span i" +
"mg{\r\n    padding:2px;\r\n    background:#ccc;\r\n}\r\nul.enlarge li:hover span{ \r\n    " +
"top: -300px; \r\n    left: -20px; \r\n}\r\nul.enlarge li:hover:nth-child(2) span{\r\n   " +
" left: -100px; \r\n}\r\nul.enlarge li:hover:nth-child(3) span{\r\n    left: -200px; \r\n" +
"}\r\n   \r\nul.enlarge img, ul.enlarge span{\r\n    behavior: url(pie/PIE.htc); \r\n}\r\n<" +
"/style>\r\n\r\n \r\n<ul");

WriteLiteral(" class=\"enlarge\"");

WriteLiteral(">\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2216), Tuple.Create("\"", 2239)
, Tuple.Create(Tuple.Create("", 2223), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Manage")
, 2223), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2271), Tuple.Create("\"", 2299)
, Tuple.Create(Tuple.Create("", 2277), Tuple.Create<System.Object, System.Int32>(Href("~/Images/PhanQuyen.png")
, 2277), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Dechairs\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Phân quyền người dùng\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2416), Tuple.Create("\"", 2444)
, Tuple.Create(Tuple.Create("", 2422), Tuple.Create<System.Object, System.Int32>(Href("~/Images/PhanQuyen.png")
, 2422), false)
);

WriteLiteral(" alt=\"Deckchairs\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2499), Tuple.Create("\"", 2525)
, Tuple.Create(Tuple.Create("", 2506), Tuple.Create<System.Object, System.Int32>(Href("~/QLDanhMuc/DanhMuc")
, 2506), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2557), Tuple.Create("\"", 2583)
, Tuple.Create(Tuple.Create("", 2563), Tuple.Create<System.Object, System.Int32>(Href("~/Images/DanhMuc.png")
, 2563), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool sunset\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý Danh mục\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2703), Tuple.Create("\"", 2729)
, Tuple.Create(Tuple.Create("", 2709), Tuple.Create<System.Object, System.Int32>(Href("~/Images/DanhMuc.png")
, 2709), false)
);

WriteLiteral(" alt=\"Blackpool sunset\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2790), Tuple.Create("\"", 2818)
, Tuple.Create(Tuple.Create("", 2797), Tuple.Create<System.Object, System.Int32>(Href("~/QLTTNhanSu/HSNhanSu")
, 2797), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2850), Tuple.Create("\"", 2880)
, Tuple.Create(Tuple.Create("", 2856), Tuple.Create<System.Object, System.Int32>(Href("~/Images/SoYeuLyLich.png")
, 2856), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý Sơ yếu lý lịch\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3004), Tuple.Create("\"", 3034)
, Tuple.Create(Tuple.Create("", 3010), Tuple.Create<System.Object, System.Int32>(Href("~/Images/SoYeuLyLich.png")
, 3010), false)
);

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<!--\r\n<li>\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3101), Tuple.Create("\"", 3126)
, Tuple.Create(Tuple.Create("", 3107), Tuple.Create<System.Object, System.Int32>(Href("~/Images/HocTap.png")
, 3107), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    <br />Quản lý quá trình Học tập\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3243), Tuple.Create("\"", 3268)
, Tuple.Create(Tuple.Create("", 3249), Tuple.Create<System.Object, System.Int32>(Href("~/Images/HocTap.png")
, 3249), false)
);

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3329), Tuple.Create("\"", 3355)
, Tuple.Create(Tuple.Create("", 3335), Tuple.Create<System.Object, System.Int32>(Href("~/Images/LamViec.png")
, 3335), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Dechairs\"");

WriteLiteral(" />\r\n    <br />Quản lý quá trình Làm việc\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3467), Tuple.Create("\"", 3493)
, Tuple.Create(Tuple.Create("", 3473), Tuple.Create<System.Object, System.Int32>(Href("~/Images/LamViec.png")
, 3473), false)
);

WriteLiteral(" alt=\"Deckchairs\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n-->\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3553), Tuple.Create("\"", 3587)
, Tuple.Create(Tuple.Create("", 3560), Tuple.Create<System.Object, System.Int32>(Href("~/TuyenDung/TuyenDung/Index")
, 3560), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3619), Tuple.Create("\"", 3647)
, Tuple.Create(Tuple.Create("", 3625), Tuple.Create<System.Object, System.Int32>(Href("~/Images/TuyenDung.png")
, 3625), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool sunset\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý quá trình Tuyển dụng\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3779), Tuple.Create("\"", 3807)
, Tuple.Create(Tuple.Create("", 3785), Tuple.Create<System.Object, System.Int32>(Href("~/Images/TuyenDung.png")
, 3785), false)
);

WriteLiteral(" alt=\"Blackpool sunset\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3868), Tuple.Create("\"", 3907)
, Tuple.Create(Tuple.Create("", 3875), Tuple.Create<System.Object, System.Int32>(Href("~/HDLaoDong/HDNguoiLaoDong/Index")
, 3875), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3939), Tuple.Create("\"", 3962)
, Tuple.Create(Tuple.Create("", 3945), Tuple.Create<System.Object, System.Int32>(Href("~/Images/HDLD.png")
, 3945), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý Hợp Đồng Lao Động\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4089), Tuple.Create("\"", 4112)
, Tuple.Create(Tuple.Create("", 4095), Tuple.Create<System.Object, System.Int32>(Href("~/Images/HDLD.png")
, 4095), false)
);

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4171), Tuple.Create("\"", 4201)
, Tuple.Create(Tuple.Create("", 4178), Tuple.Create<System.Object, System.Int32>(Href("~/QLTinhLuong/HeSoLuong")
, 4178), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4233), Tuple.Create("\"", 4261)
, Tuple.Create(Tuple.Create("", 4239), Tuple.Create<System.Object, System.Int32>(Href("~/Images/HesoLuong.png")
, 4239), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý Hệ số lương\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4382), Tuple.Create("\"", 4410)
, Tuple.Create(Tuple.Create("", 4388), Tuple.Create<System.Object, System.Int32>(Href("~/Images/HesoLuong.png")
, 4388), false)
);

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<!--\r\n<li>\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4477), Tuple.Create("\"", 4507)
, Tuple.Create(Tuple.Create("", 4483), Tuple.Create<System.Object, System.Int32>(Href("~/Images/DanhGiaKLCV.png")
, 4483), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Dechairs\"");

WriteLiteral(" />\r\n    <br />Đánh giá Hiệu Quả Công Việc\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4620), Tuple.Create("\"", 4650)
, Tuple.Create(Tuple.Create("", 4626), Tuple.Create<System.Object, System.Int32>(Href("~/Images/DanhGiaKLCV.png")
, 4626), false)
);

WriteLiteral(" alt=\"Deckchairs\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4707), Tuple.Create("\"", 4734)
, Tuple.Create(Tuple.Create("", 4713), Tuple.Create<System.Object, System.Int32>(Href("~/Images/LyLichKH.png")
, 4713), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool sunset\"");

WriteLiteral(" />\r\n    <br />Quản lý Lý lịch Khoa Học\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4852), Tuple.Create("\"", 4879)
, Tuple.Create(Tuple.Create("", 4858), Tuple.Create<System.Object, System.Int32>(Href("~/Images/LyLichKH.png")
, 4858), false)
);

WriteLiteral(" alt=\"Blackpool sunset\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n-->\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4945), Tuple.Create("\"", 4980)
, Tuple.Create(Tuple.Create("", 4952), Tuple.Create<System.Object, System.Int32>(Href("~/QLBHXH/NhanVienBHXH/Index2")
, 4952), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5012), Tuple.Create("\"", 5035)
, Tuple.Create(Tuple.Create("", 5018), Tuple.Create<System.Object, System.Int32>(Href("~/Images/BHXH.png")
, 5018), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý BHXH\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5149), Tuple.Create("\"", 5172)
, Tuple.Create(Tuple.Create("", 5155), Tuple.Create<System.Object, System.Int32>(Href("~/Images/BHXH.png")
, 5155), false)
);

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n<li>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5231), Tuple.Create("\"", 5265)
, Tuple.Create(Tuple.Create("", 5238), Tuple.Create<System.Object, System.Int32>(Href("~/QLVayMuon/NhanVienVayMuon")
, 5238), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5297), Tuple.Create("\"", 5323)
, Tuple.Create(Tuple.Create("", 5303), Tuple.Create<System.Object, System.Int32>(Href("~/Images/VayMuon.png")
, 5303), false)
);

WriteLiteral(" width=\"150px\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </a>\r\n    <br />Quản lý Vay mượn\r\n    <span>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5441), Tuple.Create("\"", 5467)
, Tuple.Create(Tuple.Create("", 5447), Tuple.Create<System.Object, System.Int32>(Href("~/Images/VayMuon.png")
, 5447), false)
);

WriteLiteral(" alt=\"Blackpool pier\"");

WriteLiteral(" />\r\n    </span>\r\n</li>\r\n\r\n</ul>\r\n    ");

WriteLiteral("\r\n\r\n</div>\r\n\r\n<script>\r\n    $(function () {\r\n        $(\".main-content\").css(\"back" +
"ground-color\", \"rgb(98, 111, 180)\");\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
