#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.DanhMuc
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\DanhMuc\Edit.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DanhMuc/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.QLDanhMuc.Models.DanhMuc>
    {
        public Edit()
        {
        }
        public override void Execute()
        {


WriteLiteral("<script src=\"~/Scripts/jquery.validate.unobtrusive.js\"></script>\r\n");


            
            #line 4 "..\..\Views\DanhMuc\Edit.cshtml"
  
    var DM = ViewBag.DanhMuc as string;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 8 "..\..\Views\DanhMuc\Edit.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\DanhMuc\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\DanhMuc\Edit.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dm");


            
            #line 12 "..\..\Views\DanhMuc\Edit.cshtml"
              Write(DM);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n\r\n        ");


            
            #line 14 "..\..\Views\DanhMuc\Edit.cshtml"
   Write(Html.Hidden("dm", DM));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 15 "..\..\Views\DanhMuc\Edit.cshtml"
   Write(Html.HiddenFor(model => model.id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 18 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.LabelFor(model => model.maDanhMuc, "Mã"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 21 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.EditorFor(model => model.maDanhMuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 22 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.maDanhMuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 26 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.LabelFor(model => model.tenDanhMuc, "Tên " + Html.VN(DM)));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 29 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.EditorFor(model => model.tenDanhMuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 30 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.tenDanhMuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 34 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.LabelFor(model => model.stt, "Số thứ tự"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 37 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.EditorFor(model => model.stt));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 38 "..\..\Views\DanhMuc\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.stt));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <p>\r\n            <input class=\"dialog\" type=\"submit\" " +
"value=\"Lưu\" />\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 45 "..\..\Views\DanhMuc\Edit.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
