#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.DanhMuc
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\DanhMuc\List.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DanhMuc/List.cshtml")]
    public partial class List : System.Web.Mvc.WebViewPage<IEnumerable<string>>
    {

public System.Web.WebPages.HelperResult link4DanhMuc(string name, bool isdef = true)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 8 "..\..\Views\DanhMuc\List.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <a name=\"");



#line 9 "..\..\Views\DanhMuc\List.cshtml"
WriteTo(@__razor_helper_writer, name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" href=\"");



#line 9 "..\..\Views\DanhMuc\List.cshtml"
WriteTo(@__razor_helper_writer, String.Format(isdef ? "DanhMuc/Index/{0}" : "/QLDanhMuc/{0}/Index", name));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 9 "..\..\Views\DanhMuc\List.cshtml"
                                                                       WriteTo(@__razor_helper_writer, Html.VN(name));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 10 "..\..\Views\DanhMuc\List.cshtml"

#line default
#line hidden

});

}


        public List()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


            
            #line 4 "..\..\Views\DanhMuc\List.cshtml"
  
    ViewBag.Title = "Quản lý danh mục";


            
            #line default
            #line hidden


WriteLiteral("\r\n\r\n<table>\r\n<tr valign=\"top\">\r\n<td style=\"padding:0\">\r\n<div id=\"accordionResizer" +
"\" class=\"list\">\r\n    <table id=\"listDanhMuc\">\r\n        <thead>\r\n            <tr>" +
"<td>Quản lý danh mục</td></tr>\r\n        </thead>\r\n        <tbody>\r\n");


            
            #line 21 "..\..\Views\DanhMuc\List.cshtml"
         foreach (var danhmuc in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr><td>");


            
            #line 23 "..\..\Views\DanhMuc\List.cshtml"
               Write(link4DanhMuc(danhmuc.Substring(2, danhmuc.Length-2)));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 24 "..\..\Views\DanhMuc\List.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"        <tr><td>
            <a name=""TaiNguyen"" href=""TaiNguyen/Index"" target=""_blank"">Thư mục/Tập tin</a>
        </td></tr>
        </tbody>
    </table>
</div>
</td>
<td width=""100%"" style=""padding:0"">
<div id = ""dialog""></div>
<div id=""tabs"">
    <ul></ul>
</div>
</td>
</tr>
</table>

");


DefineSection("Scripts", () => {

WriteLiteral("\r\n<style>\r\nth { font-size: 1.1em; }\r\nlabel { font-size: 1.1em; }\r\n#dialog label {" +
" margin-top: 0.5em; }\r\n#dialog label, #dialog input { display: block; }\r\n#dialog" +
" input, #dialog textarea { width: 95%; }\r\n#tabs li .ui-icon-close { float: right" +
"; margin: 0; cursor: pointer; }\r\n#tabs li .ui-icon-refresh { float: right; margi" +
"n: 0; cursor: pointer; }\r\n.DataTables_sort_icon { display: inline-table; }\r\n.lis" +
"t a { background: none; color: #999; text-decoration: none; }\r\n.list a:hover { c" +
"olor: #333; text-decoration: underline blink; }\r\n#listDanhMuc tr.odd td { backgr" +
"ound-color: #c4ffc4; }\r\n#listDanhMuc tr.even td { background-color: #d5ffd5; }\r\n" +
"</style>\r\n<script>\r\n    $.ajaxSetup({ cache: false });\r\n    var pWidth = \"220px\"" +
";\r\n    $(function () {\r\n        $(\"#listDanhMuc\").dataTable({\r\n            \"bJQu" +
"eryUI\": true,\r\n            \"bStateSave\": true,\r\n            \"bAutoWidth\": false," +
"\r\n            \"iDisplayLength\": 1000,\r\n            \"aoColumnDefs\": [{ \"sWidth\": " +
"pWidth, \"aTargets\": [\"_all\"]}],\r\n            \"fnDrawCallback\": function (oSettin" +
"gs) {\r\n                $(\".list a\").click(function () {\r\n                    if " +
"($(this).prop(\"target\") != \"_blank\") {\r\n                        $(\"html, body\")." +
"animate({ scrollTop: 0 }, \"slow\");\r\n                        addTab(this.name, $(" +
"this).text(), this.href);\r\n                        return false;\r\n              " +
"      }\r\n                });\r\n            }\r\n        }).rowReordering();\r\n      " +
"  $(\"#listDanhMuc_length\").hide();\r\n        $(\"#listDanhMuc_filter input\").width" +
"(\"190px\");\r\n    });\r\n    $(function () {\r\n        $(\"#accordionResizer\").resizab" +
"le({\r\n            minWidth: 210,\r\n            create: function (event, ui) {\r\n  " +
"              if ($.cookie(\"accordionWidth\") != undefined) {\r\n                  " +
"  $(this).css(\"width\", $.cookie(\"accordionWidth\"));\r\n                    $(\"#acc" +
"ordion\").accordion(\"refresh\");\r\n                } else {\r\n                    $(" +
"this).css(\"width\", pWidth);\r\n                    $(\"#accordion\").accordion(\"refr" +
"esh\");\r\n                }\r\n            },\r\n            resize: function (event, " +
"ui) {\r\n                $.cookie(\"accordionWidth\", ui.size.width);\r\n             " +
"   $(\"#accordion\").accordion(\"refresh\");\r\n            }\r\n        });\r\n    });\r\n " +
"   $(function () {\r\n        var tabs = $(\"#tabs\").tabs();\r\n        // close icon" +
": removing the tab on click\r\n        tabs.delegate(\"span.ui-icon-close\", \"click\"" +
", function () {\r\n            var panelId = $(this).closest(\"li\").remove().attr(\"" +
"aria-controls\");\r\n            $(\"#\" + panelId).remove();\r\n            tabs.tabs(" +
"\"refresh\");\r\n        }); /*\r\n        tabs.bind(\"keyup\", function (event) {\r\n    " +
"        if (event.altKey && event.keyCode === $.ui.keyCode.BACKSPACE) {\r\n       " +
"         var panelId = tabs.find(\".ui-tabs-active\").remove().attr(\"aria-controls" +
"\");\r\n                $(\"#\" + panelId).remove();\r\n                tabs.tabs(\"refr" +
"esh\");\r\n            }\r\n        });*/\r\n        tabs.delegate(\"span.ui-icon-refres" +
"h\", \"click\", function () {\r\n            var panelId = $(this).closest(\"li\").attr" +
"(\"aria-controls\");\r\n            var elem = $(\"#\" + panelId);\r\n            reload" +
"(elem, elem.attr(\"content\"));\r\n        });\r\n    });\r\n    var tabTemplate = \"<li>" +
"<a href=\'#{href}\'>#{label}</a><span class=\'ui-icon ui-icon-close\' role=\'presenta" +
"tion\'>Remove Tab</span><span class=\'ui-icon ui-icon-refresh\' role=\'presentation\'" +
">Refresh Tab</span></li>\";\r\n    function select(name) {\r\n        var tabs = $(\"#" +
"tabs\");\r\n        var parent = tabs.children(0);\r\n        for (id = 0; id < paren" +
"t.length; id++)\r\n            if (parent[id].id == \"tabs-\" + name)\r\n             " +
"   tabs.tabs(\"option\", \"active\", id - 1);\r\n    }\r\n    function addevt(elem, cont" +
"ent) {\r\n        elem.find(\"a.dopost\").click(function (event) {\r\n            even" +
"t.preventDefault();\r\n            elem = $(this).closest(\"[id*=\'tabs-\']\");\r\n     " +
"       content = elem.attr(\"content\");\r\n            if (confirm(\"Are you sure yo" +
"u want to remove this element?\"))\r\n                $.ajax({\r\n                   " +
" type: \"POST\",\r\n                    url: this.href,\r\n                    success" +
": function (data) {\r\n                        if (data.indexOf(\"OK\") == 0)\r\n     " +
"                       reload(elem, content);\r\n                        else aler" +
"t(data);\r\n                    },\r\n                    error: function (jqXHR, te" +
"xtStatus, errorThrown) {\r\n                        addTabError(errorThrown, jqXHR" +
".responseText);\r\n                    }\r\n                });\r\n        });\r\n      " +
"  elem.find(\"a.dialog\").click(function (event) {\r\n            event.preventDefau" +
"lt();\r\n            elem = $(this).closest(\"[id*=\'tabs-\']\");\r\n            content" +
" = elem.attr(\"content\");\r\n            $(\"#dialog\").load(this.href, function (res" +
"ponse, status, xhr) {\r\n                $(this).find(\"input.dialog\").click(functi" +
"on (event) {\r\n                    var form = $(this).closest(\"form\");\r\n         " +
"           if (form.valid()) {\r\n                        $.ajax({\r\n              " +
"              type: \"POST\",\r\n                            url: form.attr(\"action\"" +
"),\r\n                            data: form.serialize(),\r\n                       " +
"     success: function (data) {\r\n                                if (data.indexO" +
"f(\"OK\") == 0) {\r\n                                    $(\"#dialog\").dialog(\"close\"" +
");\r\n                                    reload(elem, content);\r\n                " +
"                } else alert(data);\r\n                            },\r\n           " +
"                 error: function (jqXHR, textStatus, errorThrown) {\r\n           " +
"                     addTabError(errorThrown, jqXHR.responseText);\r\n            " +
"                }\r\n                        });\r\n                        return f" +
"alse;\r\n                    }\r\n                });\r\n            }).dialog({\r\n    " +
"            modal: true,\r\n                width: \"auto\",\r\n                title:" +
" $(this).attr(\"title\"),\r\n                close: function () { $(\"#dialog\").empty" +
"(); }\r\n            });\r\n        });\r\n    }\r\n    function reload(elem, content) {" +
"\r\n        elem.attr(\"content\", content);\r\n        elem.block({ message: \"Loading" +
"...\" });\r\n        elem.load(content, function (response, status, xhr) {\r\n       " +
"     elem.html(response);\r\n            elem.unblock();\r\n            addevt(elem," +
" content);\r\n            elem.find(\"table.dataTable\").each(function () {\r\n       " +
"         $(this).attr(\"elem\", elem);\r\n                $(this).attr(\"link\", conte" +
"nt);\r\n                $(this).dataTable().fnSettings().aoDrawCallback.push({\r\n  " +
"                  \"fn\": function () {\r\n                        addevt($(this).at" +
"tr(\"elem\"), $(this).attr(\"link\"));\r\n                    }\r\n                });\r\n" +
"            });\r\n        });\r\n    }\r\n    function addTab(name, label, content) {" +
"\r\n        var tabs = $(\"#tabs\"), id = \"tabs-\" + name,\r\n        li = $(tabTemplat" +
"e.replace(/#\\{href\\}/g, \"#\" + id).replace(/#\\{label\\}/g, label));\r\n\r\n        var" +
" elem = $(\"#\" + id);\r\n        if (elem.length == 0) {\r\n            tabs.find(\".u" +
"i-tabs-nav\").append(li);\r\n            tabs.append(\"<div id=\'\" + id + \"\' style=\'p" +
"adding:0\'></div>\");\r\n            tabs.tabs(\"refresh\");\r\n            elem = $(\"#\"" +
" + id);\r\n            reload(elem, content);\r\n        }\r\n        select(name);\r\n " +
"   }\r\n    function addTabError(label, content) {\r\n        var name = Math.floor(" +
"1 / Math.random());\r\n        var tabs = $(\"#tabs\"), id = \"tabs-\" + name,\r\n      " +
"  li = $(tabTemplate.replace(/#\\{href\\}/g, \"#\" + id).replace(/#\\{label\\}/g, labe" +
"l));\r\n\r\n        tabs.find(\".ui-tabs-nav\").append(li);\r\n        tabs.append(\"<div" +
" id=\'\" + id + \"\'></div>\");\r\n        tabs.tabs(\"refresh\");\r\n        $(\"#\" + id).h" +
"tml(content);\r\n\r\n        select(name);\r\n    }\r\n</script>\r\n");


});


        }
    }
}
#pragma warning restore 1591
