#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.NhanVienBHXH
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    using HRM.QLBHXH.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NhanVienBHXH/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.QLBHXH.Models.nvbhNhanVienBHXH>
    {
        public Edit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\NhanVienBHXH\Edit.cshtml"
  
    ViewBag.Title = "Chỉnh sửa";
    var db = new HRMDB1Entities();
    var db1 = new HRM.Databases.Models.HRMDBEntities();
    int idnv = ViewBag.idnv;

    var tnbhxh = ViewBag.tnbhxh;

    var ttbhxh = ViewBag.ttbhxh;
    var tnbhtn = ViewBag.tnbhtn;
    var ttbhtn = ViewBag.ttbhtn;
    var dc = ViewBag.dc;
    var hsl = ViewBag.hsl;
    var cd = ViewBag.cd;
    var dv = ViewBag.dv;
 
    
    
    


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>\r\n    Chỉnh sửa thông tin BHXH của\r\n    ");


            
            #line 27 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(db.nvbhNhanVienBHXH.First(k => k.id == idnv).HoVaTen);

            
            #line default
            #line hidden
WriteLiteral("\r\n</h2>\r\n");


            
            #line 29 "..\..\Views\NhanVienBHXH\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                 
    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.NV_id));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.TGBHXHBHYT));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                              
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.TGBHTN));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                          
    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.id));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.MANV));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                        
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.SoBHXH));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                          
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.CMND));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                        
    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.HoVaTen));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                           



    
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.HiddenFor(model => model.NgaySinh));

            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                            

            
            #line default
            #line hidden
WriteLiteral("    <b>1) Mã NV</b> \r\n");


            
            #line 45 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.TextBoxFor(model => model.MANV, new { style = "width: 100px", disabled = "disabled", @class = "text" }));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                                                 
    
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.MANV));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                   

            
            #line default
            #line hidden
WriteLiteral("    <b>2) Đơn vị</b> \r\n");


            
            #line 48 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    

  
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(dv);

            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\NhanVienBHXH\Edit.cshtml"
     

            
            #line default
            #line hidden
WriteLiteral("           <b> 3) Chức danh: </b> \r\n");


            
            #line 52 "..\..\Views\NhanVienBHXH\Edit.cshtml"
   
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(cd);

            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\NhanVienBHXH\Edit.cshtml"
       

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");



WriteLiteral("      <b>4) Hệ số lương: </b>\r\n");


            
            #line 55 "..\..\Views\NhanVienBHXH\Edit.cshtml"
      
  
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(hsl);

            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\NhanVienBHXH\Edit.cshtml"
      

            
            #line default
            #line hidden
WriteLiteral("    <b> 5) Địa chỉ TT: </b> \r\n");


            
            #line 58 "..\..\Views\NhanVienBHXH\Edit.cshtml"
   
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(dc);

            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\NhanVienBHXH\Edit.cshtml"
      

  


            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");



WriteLiteral("    <br />\r\n");


            
            #line 64 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    //so nam tg BHXH 

            
            #line default
            #line hidden
WriteLiteral("       <div  style=\"background:\t#F2FFFF\"> \r\n       <i> \r\n <a ><b>  6) Thời gian t" +
"ham gia BHXH</b></a> \r\n\r\n    <br />\r\n    <b>TG tham gia BHXH tại trường</b> \r\n  " +
"  ");


            
            #line 71 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.TextBoxFor(model => model.ThoiGianThamGiaBHXHTaiTruong, "{0:dd/MM/yyyy}", new { style = "width: 100px", @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 72 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.ThoiGianThamGiaBHXHTaiTruong));

            
            #line default
            #line hidden
WriteLiteral("\r\n       \r\n          <br />\r\n      Tổng TG tham gia BHXH trước khi về trường :<b>" +
"<font color=\"green\"> ");


            
            #line 75 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                    Write(Html.TextBoxFor(model => model.SoNamThamGiaBHXHTruocVeTruong, new { style = "width: 20px", @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral(" năm, ");


            
            #line 75 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                                                                                                                        Write(Html.TextBoxFor(model => model.SoThangThamGiaBHXHTruocVeTruong, new { style = "width: 20px", @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral(" tháng </font></b>\r\n   \r\n\r\n       <br />\r\nTổng thời gian tham gia BHXH tại trường" +
":  <b><font color=\"green\"> ");


            
            #line 79 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                             Write(tnbhxh);

            
            #line default
            #line hidden
WriteLiteral(" năm, ");


            
            #line 79 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                          Write(ttbhxh);

            
            #line default
            #line hidden
WriteLiteral(" tháng</font></b>\r\n   <br />\r\n      Tổng thời gian tham gia BHXH:<b><font color=\"" +
"green\"> ");


            
            #line 81 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                      Write(Html.DisplayFor(model => model.SoNamThamGiaBHXH));

            
            #line default
            #line hidden
WriteLiteral(" năm, ");


            
            #line 81 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                                             Write(Html.DisplayFor(model => model.SoThangThamGiaBHXH));

            
            #line default
            #line hidden
WriteLiteral(" tháng </font></b>\r\n   </i>\r\n  </div>\r\n");



WriteLiteral("    <br />\r\n");


            
            #line 85 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    //so nam tg BHXH 

            
            #line default
            #line hidden
WriteLiteral("     <div style=\"background:#F2FFFF\"> \r\n     <i>\r\n <a ><b> 7)Thời gian tham gia B" +
"HTN</b></a> \r\n\r\n    <br />\r\n    <b>TG tham gia BHTN tại trường</b> \r\n    ");


            
            #line 92 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.TextBoxFor(model => model.ThoiGianThamGiaBHTNTaiTruong, "{0:dd/MM/yyyy}", new { style = "width: 100px", @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 93 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.ThoiGianThamGiaBHTNTaiTruong));

            
            #line default
            #line hidden
WriteLiteral("\r\n         <br />\r\n      Tổng TG tham gia BHTN trước khi về trường :<b><font colo" +
"r=\"green\"> ");


            
            #line 95 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                    Write(Html.TextBoxFor(model => model.SoNamThamGiaBHTNTruocVeTruong, new { style = "width: 20px", @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral(" năm, ");


            
            #line 95 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                                                                                                                        Write(Html.TextBoxFor(model => model.SoThangThamGiaBHTNTruocVeTruong, new { style = "width: 20px", @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral(" tháng </font></b>\r\n   \r\n      <br />\r\n    Tổng thời gian tham gia BHTN tại trườn" +
"g:  <b><font color=\"green\"> ");


            
            #line 98 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                 Write(tnbhtn);

            
            #line default
            #line hidden
WriteLiteral(" năm, ");


            
            #line 98 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                              Write(ttbhtn);

            
            #line default
            #line hidden
WriteLiteral(" tháng</font></b>\r\n       <br />\r\n      Tổng thời gian tham gia BHTN:<b><font col" +
"or=\"green\"> ");


            
            #line 100 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                      Write(Html.DisplayFor(model => model.SoNamThamGiaBHTNT));

            
            #line default
            #line hidden
WriteLiteral(" năm, ");


            
            #line 100 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                                              Write(Html.DisplayFor(model => model.SoThangThamGiaBHTN));

            
            #line default
            #line hidden
WriteLiteral(" tháng </font></b>\r\n    \r\n    <br />\r\n    </i>\r\n        </div>\r\n");



WriteLiteral("        <br />\r\n");


            
            #line 106 "..\..\Views\NhanVienBHXH\Edit.cshtml"
   

            
            #line default
            #line hidden
WriteLiteral("    <b>8) Số BHXH</b> \r\n");


            
            #line 108 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.TextBoxFor(model => model.SoBHXH, new { style = "width: 100px", @class = "text" }));

            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                            
    
            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.SoBHXH));

            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                     

            
            #line default
            #line hidden
WriteLiteral("    <b>9) Số KCB</b> \r\n");


            
            #line 111 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.TextBoxFor(model => model.SoKCB, new { style = "width: 100px", @class = "text" }));

            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                           
    
            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.SoKCB));

            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                    
 
  

            
            #line default
            #line hidden
WriteLiteral("    <b>10) Nơi KCB</b> \r\n");


            
            #line 116 "..\..\Views\NhanVienBHXH\Edit.cshtml"

 
            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.DropDownListFor(model => model.iddmNoiKCB, new SelectList(db.dmNoiKCB, "id", "tenbv"), "-- Chọn nơi KCB --", new { @id = "noiKCB", @class = "text" }));

            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                                                                                            
    
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.DiaChiTT));

            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                       
 

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");


            
            #line 121 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <b>11) Ghi chú</b> \r\n");


            
            #line 123 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.TextBoxFor(model => model.GhiChu, new { style = "width: 500px", @class = "text" }));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                                                            
    
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\NhanVienBHXH\Edit.cshtml"
Write(Html.ValidationMessageFor(model => model.GhiChu));

            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\NhanVienBHXH\Edit.cshtml"
                                                     
       

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");



WriteLiteral("    <input type=\"submit\" value=\"Lưu\" />\r\n");


            
            #line 128 "..\..\Views\NhanVienBHXH\Edit.cshtml"
    
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    //  $(function () {\r\n    //      $(\'.Closebhxh\').click(function (" +
") { $(\"#tgbhxh\").slideToggle(\"medium\"); });\r\n    //  });\r\n    //  $(function () " +
"{\r\n    //      $(\'.Closebhtn\').click(function () { $(\"#tgbhtn\").slideToggle(\"med" +
"ium\"); });\r\n    //  });\r\n\r\n\r\n    //tu them dau phay vao so\r\n    $(\'#SoNamThamGia" +
"BHXH\').keyup(function (event) {\r\n\r\n        // skip for arrow keys\r\n        if (e" +
"vent.which >= 37 && event.which <= 40) {\r\n            event.preventDefault();\r\n " +
"       }\r\n\r\n        $(this).val(function (index, value) {\r\n            return va" +
"lue\r\n      .replace(/\\D/g, \"\")\r\n      .replace(/\\B(?=(\\d{3})+(?!\\d))/g, \"\")\r\n   " +
" ;\r\n        });\r\n    });\r\n\r\n    $(\'#HeSoLuong\').keyup(function (event) {\r\n\r\n    " +
"    // skip for arrow keys\r\n        if (event.which >= 37 && event.which <= 40) " +
"{\r\n            event.preventDefault();\r\n        }\r\n\r\n        $(this).val(functio" +
"n (index, value) {\r\n            return value\r\n      .replace(/\\D/g, \"\")\r\n      ." +
"replace(/\\B(?=(\\d{3})+(?!\\d))/g, \"\")\r\n    ;\r\n        });\r\n    });\r\n\r\n\r\n    $(\'#S" +
"oNamThamGiaBHXHTruocVeTruong\').keyup(function (event) {\r\n\r\n        // skip for a" +
"rrow keys\r\n        if (event.which >= 37 && event.which <= 40) {\r\n            ev" +
"ent.preventDefault();\r\n        }\r\n\r\n        $(this).val(function (index, value) " +
"{\r\n            return value\r\n      .replace(/\\D/g, \"\")\r\n      .replace(/\\B(?=(\\d" +
"{3})+(?!\\d))/g, \"\")\r\n    ;\r\n        });\r\n    });\r\n\r\n    $(\'#SoThangThamGiaBHXHTr" +
"uocVeTruong\').keyup(function (event) {\r\n\r\n        // skip for arrow keys\r\n      " +
"  if (event.which >= 37 && event.which <= 40) {\r\n            event.preventDefaul" +
"t();\r\n        }\r\n\r\n        $(this).val(function (index, value) {\r\n            re" +
"turn value\r\n      .replace(/\\D/g, \"\")\r\n      .replace(/\\B(?=(\\d{3})+(?!\\d))/g, \"" +
"\")\r\n    ;\r\n        });\r\n    });\r\n\r\n\r\n    $(\'#SoNamThamGiaBHTNTruocVeTruong\').key" +
"up(function (event) {\r\n\r\n        // skip for arrow keys\r\n        if (event.which" +
" >= 37 && event.which <= 40) {\r\n            event.preventDefault();\r\n        }\r\n" +
"\r\n        $(this).val(function (index, value) {\r\n            return value\r\n     " +
" .replace(/\\D/g, \"\")\r\n      .replace(/\\B(?=(\\d{3})+(?!\\d))/g, \"\")\r\n    ;\r\n      " +
"  });\r\n    });\r\n\r\n    $(\'#SoThangThamGiaBHTNTruocVeTruong\').keyup(function (even" +
"t) {\r\n\r\n        // skip for arrow keys\r\n        if (event.which >= 37 && event.w" +
"hich <= 40) {\r\n            event.preventDefault();\r\n        }\r\n\r\n        $(this)" +
".val(function (index, value) {\r\n            return value\r\n      .replace(/\\D/g, " +
"\"\")\r\n      .replace(/\\B(?=(\\d{3})+(?!\\d))/g, \"\")\r\n    ;\r\n        });\r\n    });\r\n\r" +
"\n\r\n\r\n\r\n\r\n    var dv = $(\"[id$=dsDonViEdit]\").combobox();\r\n    var kcb = $(\"[id$=" +
"dmkcb]\").combobox();\r\n\r\n\r\n\r\n    dv.change(function () {\r\n\r\n        var DV = $(\"#" +
"dsDonViEdit option:selected\").text();\r\n\r\n        $(\"[id$=DonVi]\").val(DV);\r\n    " +
"});\r\n\r\n\r\n    //DATETIME PICKER\r\n\r\n    $(\"#ThoiGianThamGiaBHTNTaiTruong\").datepic" +
"ker({\r\n        changeDay: true,\r\n        changeMonth: true,\r\n        changeYear:" +
" true\r\n    });\r\n    $(\"#ThoiGianThamGiaBHTN\").datepicker({\r\n        changeDay: t" +
"rue,\r\n        changeMonth: true,\r\n        changeYear: true\r\n    });\r\n    $(\"#Tho" +
"iGianThamGiaBHXH\").datepicker({\r\n        changeDay: true,\r\n        changeMonth: " +
"true,\r\n        changeYear: true\r\n    });\r\n\r\n    $(\"#ThoiGianThamGiaBHXHTaiTruong" +
"\").datepicker({\r\n        changeDay: true,\r\n        changeMonth: true,\r\n        c" +
"hangeYear: true\r\n    });\r\n    $(\"#ThoiGianBatDauNghiTS\").datepicker({\r\n        c" +
"hangeDay: true,\r\n        changeMonth: true,\r\n        changeYear: true\r\n    });\r\n" +
"\r\n    $(\"#ThoiGianKetThucNghiTS\").datepicker({\r\n        changeDay: true,\r\n      " +
"  changeMonth: true,\r\n        changeYear: true\r\n    });\r\n    $(\"#ThoiGianBatDauB" +
"HXH\").datepicker({\r\n        changeDay: true,\r\n        changeMonth: true,\r\n      " +
"  changeYear: true\r\n    });\r\n    $(\".text\").removeClass(\"ui-state-default\");\r\n  " +
"  $(\".text\").removeClass(\"ui-widget-content\");\r\n    $(\".text\").removeClass(\"ui-c" +
"orner-left\");\r\n    $(\".text\").removeClass(\"ui-state-default\");\r\n    $(\".text\").c" +
"ss(\"background-color\", \"transparent\");\r\n    $(\".text\").css(\"border\", \"0\").css(\"b" +
"order-bottom\", \"1px dotted\");\r\n    $(\".custom-combobox-input\").removeClass(\"ui-s" +
"tate-default\");\r\n    $(\".custom-combobox-input\").removeClass(\"ui-widget-content\"" +
");\r\n    $(\".custom-combobox-input\").removeClass(\"ui-corner-left\");\r\n    $(\".cust" +
"om-combobox-toggle\").removeClass(\"ui-state-default\");\r\n    $(\".custom-combobox-i" +
"nput\").css(\"border\", \"0\").css(\"border-bottom\", \"1px dotted\");\r\n    $(\".custom-co" +
"mbobox-input\").css(\"background-color\", \"transparent\").css(\"margin\", \"5px 0 6px 0" +
"\");\r\n \r\n \r\n</script>\r\n<style type=\"text/css\">\r\n  \r\n    #tgbhxh, #tgbhtn\r\n    {\r\n" +
"        display: none;\r\n    }\r\n    </style>");


        }
    }
}
#pragma warning restore 1591
