#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLVayMuon.Views.TapTin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\TapTin\Create.cshtml"
    using HRM.QLVayMuon.Models;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\TapTin\Create.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TapTin/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<HRM.QLVayMuon.Models.TapTin>
    {
        public Create()
        {
        }
        public override void Execute()
        {






WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\TapTin\Create.cshtml"
  
    ViewBag.Title = "Create";
    string khoanvay = ViewBag.khoanvay;
    var db = new HRMDB1Entities();
    var idkhoanvay = ViewBag.idkhoanvay;
    int? md =ViewBag.mdid;
    string tmp = ViewBag.khoanvay;
    

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\TapTin\Create.cshtml"
Write(Html.BeginDiv());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>\r\n  \r\n\r\n       <a class=\"dialog\" href=\"/QLVayMuon/khoanVay/details?id=");


            
            #line 18 "..\..\Views\TapTin\Create.cshtml"
                                                         Write(idkhoanvay);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Trở về bổ sung hồ sơ\">Trở về bổ sung hồ sơ</a>\r\n    </p>\r\n\r\n<h4>Thêm tệp" +
" tin của hồ sơ vay mượn</h4>\r\n");


            
            #line 22 "..\..\Views\TapTin\Create.cshtml"
Write(Html.StatusMessage(TempData["Message"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 23 "..\..\Views\TapTin\Create.cshtml"
Write(Html.ValidationSummary(TempData["ModelState"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 24 "..\..\Views\TapTin\Create.cshtml"
 using (Html.BeginForm("Create", "TapTin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\TapTin\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\TapTin\Create.cshtml"
                             
 
    TempData["sochungtu"]=tmp;
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\TapTin\Create.cshtml"
Write(Html.HiddenFor(model => model.tenThuMuc, new { @Value = khoanvay }));

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\TapTin\Create.cshtml"
                                                                        

 

            
            #line default
            #line hidden
WriteLiteral("        <div> Tên giấy tờ </div>\r\n");



WriteLiteral("        <div>\r\n        ");


            
            #line 34 "..\..\Views\TapTin\Create.cshtml"
   Write(Html.DropDownListFor(model => model.tengiayto, new SelectList(ViewBag.tengiay, "Value", "Text"), md));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");



WriteLiteral("\r\n        </div>\r\n");


            
            #line 37 "..\..\Views\TapTin\Create.cshtml"
     
            
            #line default
            #line hidden

            
            #line 37 "..\..\Views\TapTin\Create.cshtml"
                                                                

        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\TapTin\Create.cshtml"
   Write(Html.LabelForVN(model => model.tepDinhKem));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\TapTin\Create.cshtml"
                                                   
        
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\TapTin\Create.cshtml"
   Write(Html.TextBoxFor(model => model.tepDinhKem, new { type = "file" }));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\TapTin\Create.cshtml"
                                                                          
        
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\TapTin\Create.cshtml"
   Write(Html.ValidationMessageFor(model => model.tepDinhKem));

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\TapTin\Create.cshtml"
                                                             


            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n            <input type=\"submit\" value=\"Thêm\"  />\r\n        </p>\r\n");


            
            #line 46 "..\..\Views\TapTin\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 48 "..\..\Views\TapTin\Create.cshtml"
Write(Html.EndDiv());

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n\r\n    $(\"[id$=tengiayto\").combobox();\r\n\r\n</script>");


        }
    }
}
#pragma warning restore 1591
