#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/QLHSNhanSu.cshtml")]
    public partial class QLHSNhanSu : System.Web.Mvc.WebViewPage<dynamic>
    {
        public QLHSNhanSu()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<li><a href=""~/Home"">Trang chủ</a></li>
<li><a href=""~/QLTTNhanSu/HSNhanSu"">Nhân sự</a></li>
<li>
    <a href=""~/QLTTNhanSu/nvQTHocTap"">Học tập</a>
    <span>/</span>
    <a href=""~/QLTTNhanSu/QLTapSu"">Tập sự</a>
    <span>/</span>
    <a href=""~/QLTTNhanSu/QLThuViec"">Thử việc</a>
</li>
<li><a href=""~/QLDanhMuc/DanhMuc"">Danh mục</a></li>
");


        }
    }
}
#pragma warning restore 1591
