#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\TheDinhDanh.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\TheDinhDanh.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\TheDinhDanh.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/TheDinhDanh.cshtml")]
    public partial class TheDinhDanh : System.Web.Mvc.WebViewPage<Object>
    {
        public TheDinhDanh()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Views\Shared\TheDinhDanh.cshtml"
  
    var db = ViewBag.db as HRMDBEntities;
    var dt = db.SqlQuery("select * from dsTheDinhDanh where NV_id=@p0", ViewData["NV_id"]);
    var dsTheDinhDanh = dt.Rows.OfType<DataRow>().Select(dr => new
    {
        id = dr["id"],
        TheDinhDanh = (dr["SoThe"] as string)
            + (!String.IsNullOrEmpty(dr["NgayCap"] as string) ? " - " + dr["NgayCap"] as string : null)
            + (!String.IsNullOrEmpty(dr["tenTinhThanh"] as string) ? " - " + dr["tenTinhThanh"] as string : null)
    }).ToList();


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 17 "..\..\Views\Shared\TheDinhDanh.cshtml"
Write(Html.DropDownList(((DataColumn)ViewData["Column"]).ColumnName,
                    new SelectList(dsTheDinhDanh, "id", "TheDinhDanh", Model), String.Empty, new { @class = "readonly" }));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
