#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Webpages.Areas.Account.Views.Manage
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
    using HRM.Accounts.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
    using HRM.Webpages.Models.Trirand;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Account/Views/Manage/ManageUsersPartial.cshtml")]
    public partial class ManageUsersPartial : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ManageUsersPartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<table");

WriteLiteral(" id=\"gridUsers\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("></table>\r\n<div");

WriteLiteral(" id=\"gridUsersPager\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"tabsEditUser\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n    <ul>\r\n        <li><a");

WriteLiteral(" href=\"#tabsEditUserActions\"");

WriteLiteral(">Actions</a></li>\r\n        <li><a");

WriteLiteral(" href=\"#tabsEditUserPermission\"");

WriteLiteral(">Permission</a></li>\r\n        <li><a");

WriteLiteral(" href=\"#tabsEditUserRegister\"");

WriteLiteral(">Register</a></li>\r\n    </ul>\r\n    <div");

WriteLiteral(" id=\"tabsEditUserActions\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
   Write(Html.Partial("ResetPasswordPartial", new ResetPasswordModel()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"tabsEditUserPermission\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
   Write(Html.Partial("SetPermissionPartial", new SetPermissionModel() { Permissions = ViewBag.Permissions }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"tabsEditUserRegister\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
   Write(Html.Partial("RegisterUserPartial", new RegisterUserModel() { Account = ViewBag.Account }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 24 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
  
    var gridUsers = new Grid() {
        Caption = "List of all Users",
        Columns = new Column[] {
        new Column("Id") { Name="UserId", Sortable=false, Hidden=true },
        new Column("User name") { Name="UserName", Align=Alignment.Center, Width=200, Sortable=true },
        new Column("Creation date") { Name="CreationDate", Align=Alignment.Center, Width=200, Sortable=true },
        new Column("Last activity") { Name="LastActivityDate", Align=Alignment.Center, Width=200, Sortable=true },
        new Column("Permissions") { Name="Permissions", Sortable=false, Hidden=true }},
        Width = 600,
        RowNum = 10,
        RowList = new int[] { 10, 20, 30 },
        Pager = "gridUsersPager",
        Selected = Html.ToIntList(ViewData["gridId"]),
        onSelectRow = "onSelectRow1Users",
        loadComplete = "loadComplete1Users",
        navGrid = new Navigator("gridUsersPager")
    };
    object listUsers = null;
    using (var context = new UsersContext()) {
        listUsers = context.UserProfiles.AsEnumerable()
        .Select(user => new { UserId = user.UserId, UserName = user.UserName,
            CreationDate = user.CreationDate, LastActivityDate = user.LastActivityDate,
            Permissions = String.Join(" ", (from role in user.GetRoles() select role.RoleId).ToArray()) }).ToArray();
    }

            
            #line default
            #line hidden
WriteLiteral(@"

<script>
var GridId = 0;
var GridUsers = $(""#gridUsers"");

function onSelectRow1Users(row) {
    GridId = GridUsers.getGridParam(""selrow"");
    resetPassword(GridId, row[""UserId""], row[""UserName""]);
    registerUser(GridId);
    setPermissions(GridId, row[""UserId""], row[""UserName""], row[""Permissions""]);
}
function loadComplete1Users(data) {
    GridUsers.setSelection(gridId, true);
}
function autoHideGridUsers(tab) {
    GridUsers.setGridState($(tab).text()==""Register""?""hidden"":""visible"");
}
$(""label"").css(""font-size"", ""1em"").css(""font-weight"", ""100"");
</script>
");

            
            #line 69 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
Write(Html.jqTabs("tabsEditUser", "autoHideGridUsers"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 70 "..\..\Areas\Account\Views\Manage\ManageUsersPartial.cshtml"
Write(Html.jqGrid("gridUsers", gridUsers, listUsers));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
