#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Webpages.Areas.Account.Views.Manage
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Account/Views/Manage/RegisterUserPartial.cshtml")]
    public partial class RegisterUserPartial : System.Web.Mvc.WebViewPage<HRM.Accounts.Models.RegisterUserModel>
    {
        public RegisterUserPartial()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
 if ("RegisterUser".Equals(ViewContext.RouteData.Values["Action"])) {
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
Write(Html.StatusMessage(ViewData["Message"]));

            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
                                            
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
Write(Html.LocationAnchor("tabsEditUserRegister"));

            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
                                                
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
 using (Html.BeginForm("RegisterUser", "Manage", FormMethod.Post, new { id = "registerUserForm" }))
{

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
Write(Html.ValidationMessage("RegisterUser"));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
                                       

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
Write(Html.ValidationInfo());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("<fieldset>\r\n    <legend>Registration Form</legend>\r\n    <ol>\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
   Write(Html.Hidden("gridId"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <li>\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
       Write(Html.LabelFor(m => m.Account));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
       Write(Html.TextBoxFor(m => m.Account));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </li>\r\n        <li>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
       Write(Html.LabelFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
       Write(Html.PasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </li>\r\n        <li>\r\n");

WriteLiteral("            ");

            
            #line 26 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
       Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
       Write(Html.PasswordFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </li>\r\n    </ol>\r\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Create new account\"");

WriteLiteral(" />\r\n</fieldset>\r\n");

            
            #line 32 "..\..\Areas\Account\Views\Manage\RegisterUserPartial.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<script>\r\nfunction registerUser(gridId) {\r\n    $(\"#registerUserForm\").find(\"#grid" +
"Id\").val(gridId);\r\n}\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
