#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.PhuongXa
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\PhuongXa\Create.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PhuongXa/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<HRM.Databases.Models.dmPhuongXa>
    {
        public Create()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<script src=\"~/Scripts/jquery.validate.unobtrusive.js\"></script>\r\n\r\n");


            
            #line 6 "..\..\Views\PhuongXa\Create.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\PhuongXa\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\PhuongXa\Create.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dmPhuongXa</legend>\r\n\r\n        <input type=\"hidde" +
"n\" id=\"idQuanHuyen\" value=\"");


            
            #line 12 "..\..\Views\PhuongXa\Create.cshtml"
                                                Write(ViewBag.QuanHuyen.id);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 15 "..\..\Views\PhuongXa\Create.cshtml"
       Write(Html.LabelFor(model => model.maPhuongXa, "Mã"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 18 "..\..\Views\PhuongXa\Create.cshtml"
       Write(Html.EditorFor(model => model.maPhuongXa));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 19 "..\..\Views\PhuongXa\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.maPhuongXa));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 23 "..\..\Views\PhuongXa\Create.cshtml"
       Write(Html.LabelFor(model => model.tenPhuongXa, "Tên " + Html.VN("PhuongXa")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 26 "..\..\Views\PhuongXa\Create.cshtml"
       Write(Html.EditorFor(model => model.tenPhuongXa));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 27 "..\..\Views\PhuongXa\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.tenPhuongXa));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            <label>");


            
            #line 31 "..\..\Views\PhuongXa\Create.cshtml"
              Write(ViewBag.QuanHuyen.tenQuanHuyen);

            
            #line default
            #line hidden
WriteLiteral(",</label>\r\n            <label>");


            
            #line 32 "..\..\Views\PhuongXa\Create.cshtml"
              Write(ViewBag.QuanHuyen.dmTinhThanh.tenTinhThanh);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        </div>\r\n        <p>\r\n            <input class=\"dialog\" type=\"su" +
"bmit\" value=\"Lưu\" />\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 38 "..\..\Views\PhuongXa\Create.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
