#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.BangLuong
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\BangLuong\Create.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BangLuong/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<HRM.Databases.Models.dmBangLuong>
    {
        public Create()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<script src=\"~/Scripts/jquery.validate.unobtrusive.js\"></script>\r\n\r\n");


            
            #line 6 "..\..\Views\BangLuong\Create.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\BangLuong\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\BangLuong\Create.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dmBangLuong</legend>\r\n\r\n        <div class=\"edito" +
"r-label\">\r\n            ");


            
            #line 13 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.LabelFor(model => model.bacLuong, "Bậc"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 16 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.EditorFor(model => model.bacLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 17 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.bacLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 21 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.LabelFor(model => model.hesoLuong, "Hệ số lương"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 24 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.EditorFor(model => model.hesoLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 25 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.hesoLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 29 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.LabelFor(model => model.phuCap, "Phụ cấp thâm niên"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 32 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.EditorFor(model => model.phuCap));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 33 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.phuCap));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 37 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.LabelFor(model => model.soThang, "Số tháng giữ bậc"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 40 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.EditorFor(model => model.soThang));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 41 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.soThang));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 45 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.LabelFor(model => model.idNhomNgach, "Nhóm ngạch"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 48 "..\..\Views\BangLuong\Create.cshtml"
       Write(Html.Hidden("idNhomNgach", (ViewData["dmNhomNgach"] as dmNhomNgachVienChuc).id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 49 "..\..\Views\BangLuong\Create.cshtml"
       Write(ViewBag.dmNhomNgach.tenNhomNgachVienChuc);

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 49 "..\..\Views\BangLuong\Create.cshtml"
                                                  Write(ViewBag.dmNhomNgach.maNhomNgachVienChuc);

            
            #line default
            #line hidden
WriteLiteral(")\r\n        </div>\r\n\r\n        <p>\r\n            <input class=\"dialog\" type=\"submit\"" +
" value=\"Lưu\" />\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 56 "..\..\Views\BangLuong\Create.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
