#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTinhLuong.Views.HeSoLuong
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\HeSoLuong\Index.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\HeSoLuong\Index.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\HeSoLuong\Index.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HeSoLuong/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\HeSoLuong\Index.cshtml"
  
    ViewBag.Title = "Index";
    var name = "dsHeSoLuong";
    var db = ViewBag.db as HRMDBEntities;
    var dt = db.SqlQuery("select * from " + name  + " as tm inner join nhanvien nv on tm.nv_id=nv.id inner join dmngachvienchuc n on tm.ngach_id=n.id where nv.ngaynghiviec is null");
    var noHSL = 0;

    var Fr = new Nullable<DateTime>();
    var To = new Nullable<DateTime>();
    DateTime date;
    if (DateTime.TryParse(Request["From"], out date)) { Fr = date; }
    if (DateTime.TryParse(Request["To"], out date)) { To = date; }
    if (Fr.HasValue || To.HasValue) {
        dt = db.SqlQuery("select * from "+name+" where @p0<=ThoiGianDenHan and ThoiGianDenHan<=@p1",
        Fr.HasValue ? Fr.Value : new DateTime(1753, 1, 1), To.HasValue ? To.Value : new DateTime(9999, 12, 31));
    }


            
            #line default
            #line hidden
WriteLiteral("\r\n<p class=\"ui-state-highlight\">Danh sách HSL CB/GV/NV trường ĐHDL Văn Lang</p>\r\n" +
"<span id=\"noHSL\"></span>\r\n\r\n");


            
            #line 25 "..\..\Views\HeSoLuong\Index.cshtml"
 using (Html.BeginForm("Index", "HeSoLuong", FormMethod.Get, new { id = "Filter" }))
{
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\HeSoLuong\Index.cshtml"
Write(Html.Hidden("NV_id", 0));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\HeSoLuong\Index.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <span>Ngày đến hạn từ</span>\r\n");


            
            #line 29 "..\..\Views\HeSoLuong\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\HeSoLuong\Index.cshtml"
Write(Html.TextBox("From", Fr));

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\HeSoLuong\Index.cshtml"
                             

            
            #line default
            #line hidden
WriteLiteral("    <span>đến</span>\r\n");


            
            #line 31 "..\..\Views\HeSoLuong\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\HeSoLuong\Index.cshtml"
Write(Html.TextBox("To", To));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\HeSoLuong\Index.cshtml"
                           

            
            #line default
            #line hidden
WriteLiteral("    <input type=\"submit\" value=\"Hiển thị\" />\r\n");


            
            #line 33 "..\..\Views\HeSoLuong\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 35 "..\..\Views\HeSoLuong\Index.cshtml"
 using (Html.BeginForm("Upgrade", "HeSoLuong", FormMethod.Post, new { target = "_blank" }))
{

            
            #line default
            #line hidden
WriteLiteral("<table id=\"dsHeSoLuong\">\r\n<thead class=\"ui-widget-header\">\r\n    <tr>\r\n        <th" +
" title=\"Select ALL\">");


            
            #line 40 "..\..\Views\HeSoLuong\Index.cshtml"
                          Write(Html.CheckBox("ALL", false));

            
            #line default
            #line hidden
WriteLiteral(@"</th>
        <th>Họ tên</th>
        <th>Đơn vị</th>
        <th>Chức danh</th>
        <th>Ngạch viên chức</th>
        <th>Bậc lương</th>
        <th>Bắt đầu</th>
        <th>Đến hạn</th>
        <th>HSL</th>
    </tr>
</thead>
<tbody class=""ui-widget-content"">
");


            
            #line 52 "..\..\Views\HeSoLuong\Index.cshtml"
 foreach (DataRow dr in dt.Rows)
{

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            ");


            
            #line 56 "..\..\Views\HeSoLuong\Index.cshtml"
       Write(Html.Hidden("HSL_id", null));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 57 "..\..\Views\HeSoLuong\Index.cshtml"
       Write(Html.CheckBox("SEL", false, new { HSL_id = dr["id"] }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 60 "..\..\Views\HeSoLuong\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["HoVaTen"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            <mark data-tip=\"");


            
            #line 63 "..\..\Views\HeSoLuong\Index.cshtml"
                       Write(Html.Display(dr, dt.Columns["tenDonVi"]));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 63 "..\..\Views\HeSoLuong\Index.cshtml"
                                                                  Write(Html.Display(dr, dt.Columns["maDonVi"]));

            
            #line default
            #line hidden
WriteLiteral("</mark>\r\n        </td>\r\n        <td>\r\n            <mark data-tip=\"");


            
            #line 66 "..\..\Views\HeSoLuong\Index.cshtml"
                       Write(Html.Display(dr, dt.Columns["tenChucDanh"]));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 66 "..\..\Views\HeSoLuong\Index.cshtml"
                                                                     Write(Html.Display(dr, dt.Columns["maChucDanh"]));

            
            #line default
            #line hidden
WriteLiteral("</mark>\r\n        </td>\r\n        <td>\r\n         <mark data-tip=\"");


            
            #line 69 "..\..\Views\HeSoLuong\Index.cshtml"
                    Write(Html.Display(dr, dt.Columns["TenNgachVienChuc"]));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 69 "..\..\Views\HeSoLuong\Index.cshtml"
                                                                       Write(Html.Display(dr, dt.Columns["maNgachVienChuc"]));

            
            #line default
            #line hidden
WriteLiteral("</mark>\r\n            \r\n        </td>\r\n        <td>\r\n            ");


            
            #line 73 "..\..\Views\HeSoLuong\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["BacLuong"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 76 "..\..\Views\HeSoLuong\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["NgayBatDau"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 79 "..\..\Views\HeSoLuong\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["ThoiGianDenHan"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td class=\"");


            
            #line 81 "..\..\Views\HeSoLuong\Index.cshtml"
               Write(dr["HeSoLuong"] is DBNull ? "ui-state-error" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 82 "..\..\Views\HeSoLuong\Index.cshtml"
             if (dr["HeSoLuong"] is DBNull)
            {
                noHSL++;

            
            #line default
            #line hidden
WriteLiteral("                <a href=\"~/QLTinhLuong/HeSoLuong/Details?NV_id=");


            
            #line 85 "..\..\Views\HeSoLuong\Index.cshtml"
                                                          Write(dr["N_id"]);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"padding:0;text-decoration:blink\" target=\"_blank\">\r\n                    <" +
"span title=\"Details\" class=\"ui-icon ui-icon-grip-dotted-horizontal\" style=\"displ" +
"ay:inline-block\"></span>\r\n                </a>\r\n");


            
            #line 88 "..\..\Views\HeSoLuong\Index.cshtml"
            }
            else
            {
                if(Convert.ToDecimal(dr["HeSoLuong"]).ToString().Length>1){
                
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\HeSoLuong\Index.cshtml"
           Write(Html.ActionLink(Convert.ToDecimal(dr["HeSoLuong"]).ToString("#.##"), "Details", "HeSoLuong", new { NV_id = dr["NV_id"] }, new { target = "_blank" }));

            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\HeSoLuong\Index.cshtml"
                                                                                                                                                                     
                }
                else
                {
                     
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\HeSoLuong\Index.cshtml"
                Write(Html.ActionLink(Convert.ToDecimal(dr["HeSoLuong"]).ToString("#.00"), "Details", "HeSoLuong", new { NV_id = dr["NV_id"] }, new { target = "_blank" }));

            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\HeSoLuong\Index.cshtml"
                                                                                                                                                                          
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n    </tr>\r\n");


            
            #line 101 "..\..\Views\HeSoLuong\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</tbody>\r\n</table>\r\n");



WriteLiteral("<br />");



WriteLiteral("<input type=\"submit\" value=\"Nâng bậc lương...\" />\r\n");


            
            #line 105 "..\..\Views\HeSoLuong\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"
<script>
    $(function () {
        $(""#dsHeSoLuong"").find(""#ALL"").change(function () {
            $(""#dsHeSoLuong"").find(""[id=SEL]"").prop(""checked"", this.checked).trigger(""change"");
        });
        $(""#dsHeSoLuong"").find(""[id=SEL]"").change(function () {
            if (this.checked) $(this).prev().val($(this).attr(""HSL-id""));
            else $(this).prev().val("""");
        });
        $(""#dsHeSoLuong"").dataTable({
            ""bAutoWidth"": true,
            ""bStateSave"": true,
            ""aoColumns"": [
                { bSortable: false },
                null, null, null, null, null, null,
                { ""sType"": ""date-vn"" }, 
                { bSortable: false }
            ],
            ""aaSorting"": [[5, ""asc""]],
            ""aLengthMenu"": [[10, 25, 50, -1], [10, 25, 50, ""All""]],
            ""sDom"": '<""H""Tfr>t<""F""ip>',
            ""oTableTools"": {
                ""sSwfPath"": ""/hrm/Content/copy_csv_xls.swf"",
                ""aButtons"": [""xls"", ""print""] } 
        }).find(""th,td"").attr(""nowrap"", true);
        $(""#Filter"").find(""input[type=text]"").css(""width"", ""80px"")
                    .datepicker({ changeMonth: true, changeYear: true });
    });
</script>
");


            
            #line 136 "..\..\Views\HeSoLuong\Index.cshtml"
 if (noHSL > 0)
{

            
            #line default
            #line hidden
WriteLiteral("<script>\r\n    $(function () {\r\n        $(\"#noHSL\").text(\"Có ");


            
            #line 140 "..\..\Views\HeSoLuong\Index.cshtml"
                        Write(noHSL);

            
            #line default
            #line hidden
WriteLiteral(" nhân viên chưa có hệ số lương!\").addClass(\"ui-state-error\");\r\n    });\r\n</script>" +
"\r\n");


            
            #line 143 "..\..\Views\HeSoLuong\Index.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
