#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLVayMuon.Views.HoanVay
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\HoanVay\Edit.cshtml"
    using HRM.QLVayMuon.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\HoanVay\Edit.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HoanVay/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.QLVayMuon.Models.HoanVay>
    {
        public Edit()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\HoanVay\Edit.cshtml"
  
    ViewBag.Title = "Edit";
    var db = new HRMDB1Entities();
    int HV_id = ViewBag.HV_id;


            
            #line default
            #line hidden

            
            #line 9 "..\..\Views\HoanVay\Edit.cshtml"
Write(Html.BeginDiv());

            
            #line default
            #line hidden
WriteLiteral("\r\n<h4>Chi tiết hoàn vay: \r\n");


            
            #line 11 "..\..\Views\HoanVay\Edit.cshtml"
Write(db.HoanVay.First(k => k.id == HV_id).KhoanVay.NhanVienVayMuon.MaNV);

            
            #line default
            #line hidden
WriteLiteral(" - \r\n");


            
            #line 12 "..\..\Views\HoanVay\Edit.cshtml"
Write(db.HoanVay.First(k => k.id == HV_id).KhoanVay.NhanVienVayMuon.HoVaTen);

            
            #line default
            #line hidden
WriteLiteral(" - \r\n");


            
            #line 13 "..\..\Views\HoanVay\Edit.cshtml"
Write(db.HoanVay.First(k => k.id == HV_id).KhoanVay.NhanVienVayMuon.DonVi);

            
            #line default
            #line hidden
WriteLiteral("\r\n</h4>\r\n<h4>\r\nThuộc khoản vay: ");


            
            #line 16 "..\..\Views\HoanVay\Edit.cshtml"
            Write(db.HoanVay.First(k => k.id == HV_id).KhoanVay.SoChungTu);

            
            #line default
            #line hidden
WriteLiteral("\r\n</h4>\r\n");


            
            #line 18 "..\..\Views\HoanVay\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\HoanVay\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\HoanVay\Edit.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>HoanVay</legend>\r\n            ");


            
            #line 23 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.TextBoxFor(model => model.TrangThai, new { @Value = "true", @Type = "hidden" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 25 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.HiddenFor(model => model.idKhoanVay));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 28 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.LabelFor(model => model.SoChungTu, "Số chứng từ"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 31 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.EditorFor(model => model.SoChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 32 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.SoChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n      ");



WriteLiteral("\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 36 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.LabelFor(model => model.NgayChungTu, "Ngày chứng từ"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 39 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.EditorFor(model => model.NgayChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 40 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.NgayChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n      ");



WriteLiteral("\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 44 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.LabelFor(model => model.DienGiai, "Diễn giải"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 47 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.EditorFor(model => model.DienGiai));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 48 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.DienGiai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 51 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.LabelFor(model => model.SoTienHoan, " Số tiền hoàn"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 54 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.HiddenFor(model => model.SoTienHoan));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 55 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.SoTienHoan));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <input id=\"Hoan\" value= ");


            
            #line 57 "..\..\Views\HoanVay\Edit.cshtml"
                           Write(String.Format("{0:#,##0}", Model.SoTienHoan));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 59 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.LabelFor(model => model.SoTienLai, "Số tiền lãi"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");



WriteLiteral("\r\n            ");


            
            #line 63 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.HiddenFor(model => model.SoTienLai));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 64 "..\..\Views\HoanVay\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.SoTienLai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <input id=\"Lai\"  value= ");


            
            #line 66 "..\..\Views\HoanVay\Edit.cshtml"
                           Write(String.Format("{0:#,##0}", Model.SoTienLai));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n        <p>\r\n            <input type=\"submit\" value=\"Lưu\" onclick=\"return ch" +
"eck();\"/> \r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 71 "..\..\Views\HoanVay\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 73 "..\..\Views\HoanVay\Edit.cshtml"
Write(Html.ActionLink("Trở về danh sách hoàn vay", "Index", new { NV_id = db.HoanVay.FirstOrDefault(k => k.id == HV_id).KhoanVay.idNhanVienVayMuon }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");


            
            #line 76 "..\..\Views\HoanVay\Edit.cshtml"
Write(Html.EndDiv());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    $(\"#NgayChungTu\").datepicker({\r\n        changeMonth: true,\r\n   " +
"     changeYear: true\r\n    });\r\n    \r\n//    $(\"#idKhoanVay\").combobox();\r\n//them" +
" dau cah vao sotien\r\n $(\'#Hoan\').keyup(function (event) {\r\n\r\n        // skip for" +
" arrow keys\r\n        if (event.which >= 37 && event.which <= 40) {\r\n            " +
"event.preventDefault();\r\n        }\r\n\r\n        $(this).val(function (index, value" +
") {\r\n            return value.replace(/\\D/g, \"\").replace(/\\B(?=(\\d{3})+(?!\\d))/g" +
", \".\");\r\n        });\r\n    });\r\n    $(\"#Hoan\").keyup(function () {\r\n        //Cle" +
"ar the hidden field\r\n        $(\"#SoTienHoan\").val(\"\");\r\n        //Create char ar" +
"ray from phone number field\r\n        var charArray = $(this).val().split(\"\");\r\n " +
"       var phoneNumber = \"\";\r\n        //Iterate over each character in the char " +
"array\r\n        //and determine if it is a number\r\n        $.each(charArray, func" +
"tion (index, value) {\r\n            if (!isNaN(value) && value != \" \") {\r\n       " +
"         phoneNumber = phoneNumber + value;\r\n            }\r\n        });\r\n       " +
" //Set hidden field\r\n        $(\"#SoTienHoan\").val(phoneNumber);\r\n    });\r\n //the" +
"m dau cah vao sotien   \r\n $(\'#Lai\').keyup(function (event) {\r\n\r\n        // skip " +
"for arrow keys\r\n        if (event.which >= 37 && event.which <= 40) {\r\n         " +
"   event.preventDefault();\r\n        }\r\n\r\n        $(this).val(function (index, va" +
"lue) {\r\n            return value.replace(/\\D/g, \"\").replace(/\\B(?=(\\d{3})+(?!\\d)" +
")/g, \".\");\r\n        });\r\n    });\r\n    $(\"#Lai\").keyup(function () {\r\n        //C" +
"lear the hidden field\r\n        $(\"#SoTienLai\").val(\"\");\r\n        //Create char a" +
"rray from phone number field\r\n        var charArray = $(this).val().split(\"\");\r\n" +
"        var phoneNumber = \"\";\r\n        //Iterate over each character in the char" +
" array\r\n        //and determine if it is a number\r\n        $.each(charArray, fun" +
"ction (index, value) {\r\n            if (!isNaN(value) && value != \" \") {\r\n      " +
"          phoneNumber = phoneNumber + value;\r\n            }\r\n        });\r\n      " +
"  //Set hidden field\r\n        $(\"#SoTienLai\").val(phoneNumber);\r\n    });\r\n\r\n\r\n  " +
"  //kiem tra null sotienvay, sotienlai\r\n    function check()\r\n    {\r\n        if " +
"(document.getElementById(\'Hoan\').value==\"\"\r\n            || document.getElementBy" +
"Id(\'Hoan\').value==undefined)\r\n        {\r\n            alert (\"Vui lòng nhập số ti" +
"ền hoàn\");\r\n            return false;\r\n        }\r\n        if (document.getElemen" +
"tById(\'Lai\').value==\"\"\r\n            || document.getElementById(\'Lai\').value==und" +
"efined)\r\n        {\r\n            alert (\"Vui lòng nhập số tiền lãi\");\r\n          " +
"  return false;\r\n        }\r\n        return true;\r\n    }\r\n</script>");


        }
    }
}
#pragma warning restore 1591
