#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLVayMuon.Views.HoanVay
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\HoanVay\Index.cshtml"
    using HRM.QLVayMuon.Models;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\HoanVay\Index.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HoanVay/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<HRM.QLVayMuon.Models.HoanVay>>
    {
        public Index()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\HoanVay\Index.cshtml"
  
    ViewBag.Title = "Index";
    var db =  new HRMDB1Entities();
    var NV_id = (int)ViewBag.NV_id;    


            
            #line default
            #line hidden
WriteLiteral("    <h3 align=\"center\"><font>Danh sách hoàn vay của: ");


            
            #line 9 "..\..\Views\HoanVay\Index.cshtml"
                                                Write(db.NhanVienVayMuon.FirstOrDefault(kv => kv.id == NV_id).MaNV);

            
            #line default
            #line hidden
WriteLiteral("\r\n    - ");


            
            #line 10 "..\..\Views\HoanVay\Index.cshtml"
 Write(db.NhanVienVayMuon.FirstOrDefault(kv => kv.id == NV_id).HoVaTen);

            
            #line default
            #line hidden
WriteLiteral("\r\n    - ");


            
            #line 11 "..\..\Views\HoanVay\Index.cshtml"
 Write(db.NhanVienVayMuon.FirstOrDefault(kv => kv.id == NV_id).DonVi);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </font></h3> \r\n    ");


            
            #line 13 "..\..\Views\HoanVay\Index.cshtml"
Write(Html.StatusMessage(TempData["Message"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 14 "..\..\Views\HoanVay\Index.cshtml"
Write(Html.ValidationSummary(TempData["ModelState"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n<p>\r\n    ");


            
            #line 16 "..\..\Views\HoanVay\Index.cshtml"
Write(Html.ActionLink("Thêm hoàn vay", "Create", new { id = NV_id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<p>\r\n    ");


            
            #line 19 "..\..\Views\HoanVay\Index.cshtml"
Write(Html.ActionLink("Trở về danh sách nhân viên vay mượn", "Index", "NhanVienVayMuon"));

            
            #line default
            #line hidden
WriteLiteral(" \r\n</p>\r\n\r\n<table id = \"HoanVay\">\r\n<thead>\r\n    <tr>\r\n        <th>");


            
            #line 25 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Thuộc khoản vay"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 26 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Số chứng từ"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 27 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Ngày chứng từ"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 28 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Diễn giải"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 29 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Mục đích sử dụng"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 30 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Định mức"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 31 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Số tiền hoàn"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th>");


            
            #line 32 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.VN("Số tiền lãi"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th></th>\r\n    </tr>\r\n  </thead>\r\n  <tbody>\r\n");


            
            #line 37 "..\..\Views\HoanVay\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            ");


            
            #line 40 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.KhoanVay.SoChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 43 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.SoChungTu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 46 "..\..\Views\HoanVay\Index.cshtml"
       Write(item.NgayChungTu.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 49 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.DienGiai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n         <td>\r\n            ");


            
            #line 52 "..\..\Views\HoanVay\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.KhoanVay.dmMucDichSuDung.TenMucDich));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n         <td>\r\n");


            
            #line 55 "..\..\Views\HoanVay\Index.cshtml"
                 if (item.KhoanVay.DinhMuc == true)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span>\r\n                    Định mức\r\n                    </s" +
"pan>\r\n");


            
            #line 60 "..\..\Views\HoanVay\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span>\r\n                    Ngoài Định mức\r\n                 " +
"   </span>\r\n");


            
            #line 66 "..\..\Views\HoanVay\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n        <td>\r\n             ");


            
            #line 69 "..\..\Views\HoanVay\Index.cshtml"
        Write(String.Format("{0:#,##0}", item.SoTienHoan));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 72 "..\..\Views\HoanVay\Index.cshtml"
       Write(String.Format("{0:#,##0}", item.SoTienLai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td align=\"right\">\r\n            <a class=\"dialog\" href=\"" +
"/QLVayMuon/HoanVay/Edit?id=");


            
            #line 75 "..\..\Views\HoanVay\Index.cshtml"
                                                          Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Chỉnh sửa\"><span class=\"ui-icon ui-icon-pencil\" style=\"display:inline-bl" +
"ock\"/></a>\r\n            <a class=\"dialog\" href=\"/QLVayMuon/HoanVay/Delete?id=");


            
            #line 76 "..\..\Views\HoanVay\Index.cshtml"
                                                            Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Xóa\"><span class=\"ui-icon ui-icon-trash\" style=\"display:inline-block\"/><" +
"/a>          \r\n        </td>\r\n    </tr>\r\n");


            
            #line 79 "..\..\Views\HoanVay\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"</tbody>
</table>



<script>
    
    $(document).ready(function () {
        $(""#HoanVay"").dataTable({
            ""bAutoWidth"": true,
            ""bStateSave"": true,
            ""aLengthMenu"": [[10, 25, 50, -1], [10, 25, 50, ""All""]]
        });
    });
</script>

");


        }
    }
}
#pragma warning restore 1591
