#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Webpages.Areas.Account.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Account/Views/Shared/Account.cshtml")]
    public partial class Account : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Account()
        {
        }
        public override void Execute()
        {
WriteLiteral("<li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6), Tuple.Create("\"", 19)
, Tuple.Create(Tuple.Create("", 13), Tuple.Create<System.Object, System.Int32>(Href("~/Home")
, 13), false)
);

WriteLiteral(">Trang chủ</a></li>\r\n");

        }
    }
}
#pragma warning restore 1591
