#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.dmNoiKCB
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/dmNoiKCB/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.QLBHXH.Models.dmNoiKCB>
    {
        public Edit()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\dmNoiKCB\Edit.cshtml"
  
    ViewBag.Title = "Edit";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Sửa nơi KCB</h2>\r\n\r\n");

            
            #line 9 "..\..\Views\dmNoiKCB\Edit.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\dmNoiKCB\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\dmNoiKCB\Edit.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dmNoiKCB</legend>\r\n\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\dmNoiKCB\Edit.cshtml"
   Write(Html.HiddenFor(model => model.id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n  \r\n        <table>\r\n  <tr>\r\n    <td> Mã BV</td>\r\n    <td>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\dmNoiKCB\Edit.cshtml"
       Write(Html.EditorFor(model => model.MaBV));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\dmNoiKCB\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.MaBV));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <td> Tên bệnh viện</td>\r\n    <td>\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\dmNoiKCB\Edit.cshtml"
       Write(Html.EditorFor(model => model.TenBV));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Views\dmNoiKCB\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.TenBV));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n  <tr>\r\n    <td> Ghi chú</td>\r\n    <td>\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Views\dmNoiKCB\Edit.cshtml"
       Write(Html.EditorFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Views\dmNoiKCB\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n  </tr>\r\n</table>\r\n     \r\n\r\n       \r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Lưu\"");

WriteLiteral(" />\r\n    </fieldset>\r\n");

            
            #line 43 "..\..\Views\dmNoiKCB\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Views\dmNoiKCB\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
