#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.DanhSachDieuChinhTangGiam
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DanhSachDieuChinhTangGiam/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<HRM.QLBHXH.Models.nvbhDanhSachDieuChinhTangGiam>
    {
        public Create()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
  
    ViewBag.Title = "Create";
    ViewBag.TyLeDong = ViewBag.TyLeDong;
    ViewBag.mlttc = ViewBag.mlttc;
    ViewBag.mlttv = ViewBag.mlttv; 
    DateTime ngayht = ViewBag.ngayht;


            
            #line default
            #line hidden


WriteLiteral("\r\n");


            
            #line 11 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
                                 
  

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>nvbhDanhSachDieuChinhTangGiam</legend>");



WriteLiteral("\r\n        <span>1) Loại điều chỉnh(<font color=\"red\"><b>*</b></font>):\r\n         " +
"   ");


            
            #line 18 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.DropDownList("idLoaiDieuChinh", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 19 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.idLoaiDieuChinh));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <span id=\"clickme\"><font color=\"red\"><b>Loại:(*)</b></font>\r\n      " +
"          ");


            
            #line 21 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
           Write(Html.DropDownList("idLoaiTangGiam", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 22 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
           Write(Html.ValidationMessageFor(model => model.idLoaiTangGiam));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>2) Ngày phát sinh(<font color=\"red\"><b>*</b></font>):\r\n     " +
"       ");


            
            #line 24 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.NgayPhatSinh, new {     @class = "text" ,@Value = ngayht.ToShortDateString() }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 25 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.NgayPhatSinh));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        ");


            
            #line 28 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
   Write(Html.HiddenFor(model => model.idnvbhNhanVienBHXH, new { @Value = 1 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span>3) Họ và tên(<font color=\"red\"><b>*</b></font>):\r\n            ");


            
            #line 30 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.DropDownList("list", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 31 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.HiddenFor(model => model.NV_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 32 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.NV_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            4) Cấp bậc/ Chức vụ(<font color=\"red\"><b>*</b></font>):\r\n          " +
"  ");


            
            #line 34 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.ChucVuCongViec, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 35 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.ChucVuCongViec));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <b>5) Mức đóng cũ</b>\r\n        <br />\r" +
"\n        <span>5.1) Tiền lương:\r\n            ");


            
            #line 41 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.HiddenFor(model => model.TienLuongMDC, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 42 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.TienLuongMDC));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input id=\"Tien1\"  class = \"text\"/>\r\n        </span>\r\n        <br /" +
">\r\n        <span>5.2) Phụ cấp chức vụ:\r\n            ");


            
            #line 47 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCChucVuMDC, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 48 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCChucVuMDC));

            
            #line default
            #line hidden
WriteLiteral("\r\n            5.3) Phụ cấp thâm niên vượt khung(%):\r\n            ");


            
            #line 50 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCThamNienVuotKhungMDC, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 51 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCThamNienVuotKhungMDC));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <span>5.4) Phụ cấp thâm niên nghề(%):\r" +
"\n            ");


            
            #line 55 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCThamNienNgheMDC, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 56 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCThamNienNgheMDC));

            
            #line default
            #line hidden
WriteLiteral("\r\n            5.5) Phụ cấp Khác:\r\n            ");


            
            #line 58 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCKhacMDC, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 59 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCKhacMDC));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <b>6) Mức đóng mới</b>\r\n        <br />" +
"\r\n        <span>6.1) Tiền lương:\r\n            ");


            
            #line 65 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.HiddenFor(model => model.TienLuongMDM, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 66 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.TienLuongMDM));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input id=\"Tien2\" class = \"text\" />\r\n        </span>\r\n        <br /" +
">\r\n        <span>6.2) Phụ cấp chức vụ:\r\n            ");


            
            #line 71 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCChucVuMDM, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 72 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCChucVuMDM));

            
            #line default
            #line hidden
WriteLiteral("\r\n            6.3) Phụ cấp thâm niên vượt khung(%):\r\n            ");


            
            #line 74 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCThamNienVuotKhungMDM, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 75 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCThamNienVuotKhungMDM));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <span>6.4) Phụ cấp thâm niên nghề(%):\r" +
"\n            ");


            
            #line 79 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCThamNienNgheMDM, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 80 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCThamNienNgheMDM));

            
            #line default
            #line hidden
WriteLiteral("\r\n            6.5) Phụ cấp Khác:\r\n            ");


            
            #line 82 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.PCKhacMDM, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 83 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.PCKhacMDM));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <span>7) Từ tháng năm(<font color=\"red" +
"\"><b>*</b></font>):\r\n            ");


            
            #line 87 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.TuThangNam, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 88 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.TuThangNam));

            
            #line default
            #line hidden
WriteLiteral("\r\n            8) Đến tháng năm:\r\n            ");


            
            #line 90 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.DenThangNam, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 91 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.DenThangNam));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n   MLTTC:\r\n         ");


            
            #line 95 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
    Write(Html.DropDownList("mlttc", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");



WriteLiteral("\r\n            ");


            
            #line 97 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.MLTTC));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <br />\r\n            MLTTV:\r\n                ");


            
            #line 100 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
           Write(Html.DropDownList("mlttv", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");



WriteLiteral("\r\n            ");


            
            #line 102 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.MLTTV));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <br />\r\n            TLBHXH:\r\n                ");


            
            #line 105 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
           Write(Html.DropDownList("tlbhxh", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");



WriteLiteral("\r\n            ");


            
            #line 107 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.TLBHXH));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <br />TLBHYT:\r\n                      ");


            
            #line 109 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
                 Write(Html.DropDownList("tlbhyt", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");



WriteLiteral("\r\n            ");


            
            #line 111 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.TLBHYT));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <br />TLBHTN:\r\n                      ");


            
            #line 113 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
                 Write(Html.DropDownList("tlbhtn", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");



WriteLiteral("\r\n            ");


            
            #line 115 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.TLBHTN));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <br />\r\n        <span>\r\n            ");


            
            #line 118 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.VN("Không trả thẻ: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 119 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.EditorFor(model => model.KhongTraThe));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 120 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.KhongTraThe));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <span>\r\n            ");


            
            #line 124 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.VN("Ghi chú: "));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 125 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.TextBoxFor(model => model.GhiChu, new { @class = "text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 126 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <br />\r\n        <font color=\"red\"><b>(*)Không được để " +
"trống</b></font>\r\n        ");


            
            #line 130 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
   Write(Html.HiddenFor(model => model.idLoaiTangGiam, new { @id = "loaiTG" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <p>\r\n            <input type=\"submit\" value=\"Thêm\" onclick=\"return chec" +
"k();\" />\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 135 "..\..\Views\DanhSachDieuChinhTangGiam\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<script>\r\n    //    $(\'#idLoaiTangGiam\').hide();\r\n    var dc = $(\"[id$=idLoaiDieu" +
"Chinh]\").combobox();\r\n    var tg = $(\"[id$=idLoaiTangGiam\").combobox();\r\n    $(\"" +
"[id$=tlbhxh\").combobox();\r\n    $(\"[id$=tlbhyt\").combobox();\r\n    $(\"[id$=tlbhtn\"" +
").combobox();\r\n    $(\"[id$=mlttc\").combobox();\r\n    $(\"[id$=mlttv\").combobox();\r" +
"\n\r\n    $(\"#clickme\").hide();\r\n    dc.change(function () {\r\n        if ($(this).v" +
"al() == 1 || $(this).val() == 2) {\r\n            $(\"#clickme\").show();\r\n\r\n       " +
"     tg.trigger(\"connect\", \"~/QLBHXH/DanhSachDieuChinhTangGiam/TG?id=\" + $(this)" +
".val());\r\n        } else { $(\"#clickme\").hide(); }\r\n    });\r\n\r\n\r\n\r\n\r\n\r\n    //tho" +
"ng bao loi neu cac truong bi nill\r\n    function check() {\r\n\r\n        if (documen" +
"t.getElementById(\'idLoaiDieuChinh\').value == \"\") {\r\n            alert(\"Loại điều" +
" chỉnh không được bỏ trống!\");\r\n\r\n            return false;\r\n        }\r\n        " +
"if (document.getElementById(\'NgayPhatSinh\').value == \"\") {\r\n            alert(\"N" +
"gày phát sinh không được bỏ trống!\");\r\n\r\n            return false;\r\n        }\r\n " +
"       if (document.getElementById(\'list\').value == \"\") {\r\n            alert(\"Họ" +
" và tên không được bỏ trống!\");\r\n\r\n            return false;\r\n        }\r\n\r\n     " +
"   if (document.getElementById(\'TuThangNam\').value == \"\") {\r\n            alert(\"" +
"Từ tháng năm không được bỏ trống!\");\r\n\r\n            return false;\r\n        }\r\n\r\n" +
"\r\n    }\r\n\r\n    //    $(\"#idLoaiDieuChinh\").combobox();\r\n    //    $(\"#idLoaiTang" +
"Giam\").combobox();\r\n    $(\"#TyLeDong\").combobox();\r\n    var nvbh = $(\"#list\").co" +
"mbobox();\r\n    //    var nvbhxh = $(\"[id$=idnvbhNhanVienBHXH\").combobox();\r\n    " +
"//datetime picker\r\n    $(\"#NgayPhatSinh\").datepicker({\r\n        changeDay: true," +
"\r\n        changeMonth: true,\r\n        changeYear: true\r\n    });\r\n    $(\"#TuThang" +
"Nam\").datepicker({\r\n        changeDay: true,\r\n        changeMonth: true,\r\n      " +
"  changeYear: true\r\n    });\r\n    $(\"#DenThangNam\").datepicker({\r\n        changeD" +
"ay: true,\r\n        changeMonth: true,\r\n        changeYear: true\r\n    });\r\n\r\n\r\n\r\n" +
"//    //css\r\n//    $(\".custom-combobox-input\").removeClass(\"ui-state-default\");\r" +
"\n//    $(\".custom-combobox-input\").removeClass(\"ui-widget-content\");\r\n//    $(\"." +
"custom-combobox-input\").removeClass(\"ui-corner-left\");\r\n//    $(\".custom-combobo" +
"x-toggle\").removeClass(\"ui-state-default\");\r\n//    $(\".custom-combobox-input\").c" +
"ss(\"border\", \"0\").css(\"border-bottom\", \"1px dotted\");\r\n//    $(\".custom-combobox" +
"-input\").css(\"background-color\", \"transparent\").css(\"margin\", \"5px 0 6px 0\");\r\n/" +
"/    // Remove bg\r\n//    //    $(\"input[type=text],input[type=datetime],input[ty" +
"pe=number]\").css(\"background-color\", \"transparent\");\r\n//    //    $(\"input[type=" +
"text],input[type=datetime],input[type=number]\").css(\"border\", \"0\").css(\"border-b" +
"ottom\", \"1px dotted\");\r\n//    $(\"#Tien1\").css(\"border\", \"0\").css(\"border-bottom\"" +
", \"1px dotted\").css(\"background-color\", \"transparent\");\r\n//    $(\"#Tien2\").css(\"" +
"border\", \"0\").css(\"border-bottom\", \"1px dotted\").css(\"background-color\", \"transp" +
"arent\");\r\n//    // remove corner \r\n//    //    $(\".custom-combobox-input\").remov" +
"eClass(\"ui-state-default\");\r\n//    //    $(\".custom-combobox-input\").removeClass" +
"(\"ui-widget-content\");\r\n//    //    $(\".custom-combobox-input\").removeClass(\"ui-" +
"corner-left\");\r\n//    //    $(\".custom-combobox-toggle\").removeClass(\"ui-state-d" +
"efault\");\r\n//    // set auto size\r\n    $(\".custom-combobox-input\").on(\"input\", f" +
"unction () {\r\n        $(this).attr(\"size\", $(this).val().length + 4);\r\n    });\r\n" +
"    setInterval(function () {\r\n        $(\".custom-combobox-input\").each(function" +
" () {\r\n            $(this).attr(\"size\", $(this).val().length + 4);\r\n        });\r" +
"\n    }, 1000);\r\n//    $(\"input[type=text]\").on(\"input\", function () {\r\n//       " +
" $(this).attr(\"size\", $(this).val().length + 1);\r\n//    }).each(function () {\r\n/" +
"/        $(this).attr(\"size\", $(this).val().length + 1);\r\n//    });\r\n    $(\"inpu" +
"t[type=datetime]\").css(\"width\", \"90px\");\r\n    // set size for tex editor\r\n    $(" +
"\"#PCChucVuMDC\").css(\"width\", \"100\");\r\n    $(\"#PCThamNienVuotKhungMDC\").css(\"widt" +
"h\", \"100\");\r\n    $(\"#PCThamNienNgheMDC\").css(\"width\", \"100\");\r\n    $(\"#PCKhacMDC" +
"\").css(\"width\", \"100\");\r\n    $(\"#PCChucVuMDM\").css(\"width\", \"100\");\r\n    $(\"#PCT" +
"hamNienVuotKhungMDM\").css(\"width\", \"100\");\r\n    $(\"#PCThamNienNgheMDM\").css(\"wid" +
"th\", \"100\");\r\n    $(\"#PCKhacMDM\").css(\"width\", \"100\");\r\n    $(\"#ChucVuCongViec\")" +
".css(\"width\", \"200\");\r\n    $(\".custom-combobox-input\").css(\"background-color\", \"" +
"transparent\").css(\"margin\", \"5px 0 6px 0\");\r\n\r\n    $(\".text\").removeClass(\"ui-st" +
"ate-default\");\r\n    $(\".text\").removeClass(\"ui-widget-content\");\r\n    $(\".text\")" +
".removeClass(\"ui-corner-left\");\r\n    $(\".text\").removeClass(\"ui-state-default\");" +
"\r\n    $(\".text\").css(\"background-color\", \"transparent\");\r\n    $(\".text\").css(\"bo" +
"rder\", \"0\").css(\"border-bottom\", \"1px dotted\");\r\n    $(\".custom-combobox-input\")" +
".removeClass(\"ui-state-default\");\r\n    $(\".custom-combobox-input\").removeClass(\"" +
"ui-widget-content\");\r\n    $(\".custom-combobox-input\").removeClass(\"ui-corner-lef" +
"t\");\r\n    $(\".custom-combobox-toggle\").removeClass(\"ui-state-default\");\r\n    $(\"" +
".custom-combobox-input\").css(\"border\", \"0\").css(\"border-bottom\", \"1px dotted\");\r" +
"\n    $(\".custom-combobox-input\").css(\"background-color\", \"transparent\").css(\"mar" +
"gin\", \"5px 0 6px 0\");\r\n\r\n//    $(\"input[type=text],input[type=datetime],input[ty" +
"pe=number],.custom-combobox-input\").css(\"border\", \"0\").css(\"border-bottom\", \"1px" +
" dotted\");\r\n//    //\r\n\r\n    //-------------------------------------Tien 1-------" +
"---------------------------------------   \r\n    $(\'#Tien1\').keyup(function (even" +
"t) {\r\n        // skip for arrow keys\r\n        if (event.which >= 37 && event.whi" +
"ch <= 40) {\r\n            event.preventDefault();\r\n        }\r\n        $(this).val" +
"(function (index, value) {\r\n            return value.replace(/\\D/g, \"\").replace(" +
"/\\B(?=(\\d{3})+(?!\\d))/g, \".\");\r\n        });\r\n    });\r\n\r\n    $(\"#Tien1\").keyup(fu" +
"nction () {\r\n        //Clear the hidden field\r\n        $(\"#TienLuongMDC\").val(\"\"" +
");\r\n        //Create char array from phone number field\r\n        var charArray =" +
" $(this).val().split(\"\");\r\n        var phoneNumber = \"\";\r\n        //Iterate over" +
" each character in the char array\r\n        //and determine if it is a number\r\n  " +
"      $.each(charArray, function (index, value) {\r\n            if (!isNaN(value)" +
" && value != \" \") {\r\n                phoneNumber = phoneNumber + value;\r\n       " +
"     }\r\n        });\r\n        //Set hidden field\r\n        $(\"#TienLuongMDC\").val(" +
"phoneNumber);\r\n    });\r\n\r\n    //----------------------------- Tien 2 -----------" +
"-------------------------------------------------- \r\n    $(\'#Tien2\').keyup(funct" +
"ion (event) {\r\n        // skip for arrow keys\r\n        if (event.which >= 37 && " +
"event.which <= 40) {\r\n            event.preventDefault();\r\n        }\r\n        $(" +
"this).val(function (index, value) {\r\n            return value.replace(/\\D/g, \"\")" +
".replace(/\\B(?=(\\d{3})+(?!\\d))/g, \".\");\r\n        });\r\n    });\r\n    $(\"#Tien2\").k" +
"eyup(function () {\r\n        //Clear the hidden field\r\n        $(\"#TienLuongMDM\")" +
".val(\"\");\r\n        //Create char array from phone number field\r\n        var char" +
"Array = $(this).val().split(\"\");\r\n        var phoneNumber = \"\";\r\n        //Itera" +
"te over each character in the char array\r\n        //and determine if it is a num" +
"ber\r\n        $.each(charArray, function (index, value) {\r\n            if (!isNaN" +
"(value) && value != \" \") {\r\n                phoneNumber = phoneNumber + value;\r\n" +
"            }\r\n        });\r\n        //Set hidden field\r\n        $(\"#TienLuongMDM" +
"\").val(phoneNumber);\r\n    });\r\n\r\n    // Lấy chức vụ sau khi chọn Nhân viên đưa v" +
"ào combobox\r\n    nvbh.change(function () {\r\n        var stringValue = $(this).va" +
"l();\r\n        var list = stringValue.split(\'-\');\r\n        //        var text = $" +
"(this).val();\r\n        $(\"[id$=NV_id]\").val(list[0]);\r\n        $(\"[id$=ChucVuCon" +
"gViec]\").val(list[1]);\r\n\r\n    });\r\n\r\n</script>\r\n<style>\r\n    form\r\n    {\r\n      " +
"  width: auto;\r\n    }\r\n    input\r\n    {\r\n        width: auto;\r\n        font-weig" +
"ht: bold;\r\n    }\r\n    span\r\n    {\r\n        display: inline-block;\r\n        white" +
"-space: nowrap;\r\n    }\r\n    label\r\n    {\r\n        display: inline;\r\n        colo" +
"r: gray;\r\n        font-size: 1.1em;\r\n    }\r\n</style>\r\n");


        }
    }
}
#pragma warning restore 1591
