#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.QuyetDinh
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\QuyetDinh\Index.cshtml"
    using HRM.QLDanhMuc.Models;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\QuyetDinh\Index.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QuyetDinh/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<HRM.Databases.Models.dmQuyetDinh>>
    {
        public Index()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n<p>\r\n    ");


            
            #line 6 "..\..\Views\QuyetDinh\Index.cshtml"
Write(Html.DropDownList("loaiQuyetDinh", "Chọn loại quyết định"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <a class=\"dialog\" href=\"QuyetDinh/Create?loai=");


            
            #line 7 "..\..\Views\QuyetDinh\Index.cshtml"
                                             Write(ViewBag.loaiQuyetDinh.SelectedValue);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Thêm\">Thêm quyết định</a>\r\n</p>\r\n<table id=\"listQuyetDinh\">\r\n<thead>\r\n  " +
"  <tr>\r\n        <th>Số</th>\r\n        <th>Ngày ký</th>\r\n        <th>Nội dung</th>" +
"\r\n        <th></th>\r\n    </tr>\r\n</thead>\r\n<tbody>\r\n");


            
            #line 19 "..\..\Views\QuyetDinh\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            ");


            
            #line 22 "..\..\Views\QuyetDinh\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.MaQuyetDinh));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");


            
            #line 25 "..\..\Views\QuyetDinh\Index.cshtml"
             if (item.NgayApDung.HasValue || item.NgayKetThuc.HasValue)
            {
                var range = String.Format("{0} - {1}", item.NgayApDung.HasValue ? item.NgayApDung.Value.ToShortDateString() : "~"
                                                     , item.NgayKetThuc.HasValue ? item.NgayKetThuc.Value.ToShortDateString() : "~");

            
            #line default
            #line hidden
WriteLiteral("                <span class=\"help\" data-tip=\"");


            
            #line 29 "..\..\Views\QuyetDinh\Index.cshtml"
                                        Write(range);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 29 "..\..\Views\QuyetDinh\Index.cshtml"
                                                Write(item.NgayKy.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 30 "..\..\Views\QuyetDinh\Index.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <span>");


            
            #line 33 "..\..\Views\QuyetDinh\Index.cshtml"
                 Write(item.NgayKy.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 34 "..\..\Views\QuyetDinh\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n        <td>\r\n");


            
            #line 37 "..\..\Views\QuyetDinh\Index.cshtml"
             if (String.IsNullOrEmpty(item.GhiChu))
            {
                
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\QuyetDinh\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.NoiDung));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\QuyetDinh\Index.cshtml"
                                                           
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <span class=\"success\" data-tip=\"");


            
            #line 43 "..\..\Views\QuyetDinh\Index.cshtml"
                                           Write(item.GhiChu);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 43 "..\..\Views\QuyetDinh\Index.cshtml"
                                                         Write(item.NoiDung);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 44 "..\..\Views\QuyetDinh\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n        <td align=\"right\">\r\n            <a class=\"dopost\" href=\"Qu" +
"yetDinh/Delete?id=");


            
            #line 47 "..\..\Views\QuyetDinh\Index.cshtml"
                                                   Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Xóa\"><span class=\"ui-icon ui-icon-trash\" style=\"display:inline-block\"/><" +
"/a>\r\n            <a class=\"dialog\" href=\"QuyetDinh/Edit?id=");


            
            #line 48 "..\..\Views\QuyetDinh\Index.cshtml"
                                                 Write(item.id);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Sửa\"><span class=\"ui-icon ui-icon-pencil\" style=\"display:inline-block\"/>" +
"</a>\r\n        </td>\r\n    </tr>\r\n");


            
            #line 51 "..\..\Views\QuyetDinh\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</tbody>\r\n</table>\r\n<script>\r\n    ");


            
            #line 55 "..\..\Views\QuyetDinh\Index.cshtml"
Write(Html.dataTables("listQuyetDinh"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    $(function() {\r\n        $(\"#loaiQuyetDinh\").change(function() {\r\n          " +
"  reload($(this).parents(\".ui-tabs-panel\"), \"QuyetDinh/Index?loai=\"+$(this).val(" +
"));\r\n        });\r\n    });\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
