#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.nvQTHocTap
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    using HRM.QLTTNhanSu.Models;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/nvQTHocTap/QTChungChi.cshtml")]
    public partial class QTChungChi : System.Web.Mvc.WebViewPage<HRM.Databases.Models.nvQTChungChi>
    {
        public QTChungChi()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
  
    string prefix = null;
    ViewBag.Title = "Index";
    var db = new HRMDBEntities();
    var All = Request["All"] == "on";
    var From = new Nullable<DateTime>();
    var To = new Nullable<DateTime>();
    DateTime date;
    if (DateTime.TryParse(Request["From"], out date))
    { From = date; }
    if (DateTime.TryParse(Request["To"], out date))
    { To = date; }
    var Download = Request["Download"] == "OK";
    var Database = new List<nvQTChungChi>();


            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 19 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.ActionLink("Theo dõi học lấy văn bằng", "Index", "nvQTHocTap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 20 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.StatusMessage(TempData["Message"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 21 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
 using (Html.BeginForm("QTChungChi", "nvQTHocTap", FormMethod.Get, new { id = "Filter" }))
{

            
            #line default
            #line hidden
WriteLiteral("            <input type=\"datetime\" name=\"From\" title=\"Từ ngày\" value=\"");


            
            #line 23 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                                                 Write(From);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("        <input type=\"datetime\" name=\"To\" title=\"Đến ngày\" value=\"");


            
            #line 24 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                                            Write(To);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("        <input type=\"checkbox\" name=\"All\" ");


            
            #line 25 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                      Write(All ? "checked" : "");

            
            #line default
            #line hidden
WriteLiteral(" />");



WriteLiteral("<span>Tất cả</span>\r\n");



WriteLiteral("        <input type=\"submit\" value=\"Filter\" />\r\n");



WriteLiteral("    <a href=\"/hrm/nvQTHocTap/qtChungChi?From=");


            
            #line 27 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                        Write(Request["From"]);

            
            #line default
            #line hidden
WriteLiteral("&To=");


            
            #line 27 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                                            Write(Request["To"]);

            
            #line default
            #line hidden
WriteLiteral("&All=");


            
            #line 27 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                                                               Write(Request["All"]);

            
            #line default
            #line hidden
WriteLiteral("&Download=OK\" title=\"Download\"><img src=\"~/images/excel.gif\" /></a>\r\n");


            
            #line 28 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   
            
            #line default
            #line hidden

            
            #line 28 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                                                     
}

            
            #line default
            #line hidden
WriteLiteral(@"<table id=""example"" class=""stripe row-border order-column"" cellspacing=""0"" width=""100%"">
<thead>
    <tr>
       <th>Họ tên</th>
        <th>Đơn vị</th>
        <th>Loại chứng chỉ</th>
        <th>Tên trường</th>
        <th>Tên khóa học</th>
        <th>Quốc gia</th>
        <th>Nơi học</th>
        <th>Số QĐ</th>
        <th>Ngày cấp QĐ</th>
        <th>Chế độ</th>
        <th>Bắt đầu</th>
        <th>Kết thúc dự kiến</th>
        <th>Kết thúc chính thức</th>
        <th>Kết quả</th>
        <th>Kinh phí</th>
        <th>Chi phí khác</th>
        <th>Nhà trường<br />hỗ trợ</th>   
        <th>Hiện trạng</th>
        <th>Ghi chú</th>
        <th></th>
    </tr>
</thead>

<tbody>
");


            
            #line 57 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
      var cts = db.nvQTChungChi
        .Where(ct => ct.ThoiGianBatDau >= From || !From.HasValue)
                .Where(ct => ct.ThoiGianBatDau <= To || !To.HasValue)
                .Where(ct => !ct.ThoiGianKetThucChinhThuc.HasValue || All);
      if (All)
      {
          cts = db.nvQTChungChi;
      }
      Database.AddRange(cts); 
    

            
            #line default
            #line hidden

            
            #line 67 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   foreach (var item in cts)
  {
      ViewData.TemplateInfo.HtmlFieldPrefix = null;
      prefix = "item" + item.GetHashCode();

            
            #line default
            #line hidden
WriteLiteral(" <tr>\r\n");


            
            #line 72 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
     using (Html.BeginForm("Update_CC", "nvQTHocTap", new { From = From.HasValue ? From.Value.ToShortDateString() : "", To = To.HasValue ? To.Value.ToShortDateString() : "", All = All ? "on" : "" }))
    {     
       
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
  Write(Html.Hidden("Prefix", prefix));

            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                     
       
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
  Write(Html.Hidden("CC_id", item.id));

            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                     
        ViewData.TemplateInfo.HtmlFieldPrefix = prefix;

            
            #line default
            #line hidden
WriteLiteral("     <td>");


            
            #line 77 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    Write(item.NhanVien.nvSoYeuLyLiches.Single().HoVaTen);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("     <td>");


            
            #line 78 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    Write(item.dmDonVi.maDonVi);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("    <td> \r\n    ");


            
            #line 80 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.DropDownListFor(model => item.LoaiChungChi_id, new SelectList(db.dmLoaiChungChi, "id", "tenloaichungchi"), item.LoaiChungChi_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 81 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.ValidationMessageFor(model => item.LoaiChungChi_id));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </td>\r\n");



WriteLiteral("    <td>  \r\n     ");


            
            #line 84 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.EditorFor(model => item.TenTruong));

            
            #line default
            #line hidden
WriteLiteral("\r\n     ");


            
            #line 85 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.ValidationMessageFor(model => item.TenTruong));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    </td>\r\n");



WriteLiteral("     <td>\r\n        ");


            
            #line 88 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.TenKhoaHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 89 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.TenKhoaHoc));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </td>     \r\n");



WriteLiteral("       <td> \r\n            ");


            
            #line 92 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.DropDownListFor(model => item.QuocGia_id, new SelectList(db.dmQuocGia, "id", "tenquocgia"), item.QuocGia_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 93 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => item.QuocGia_id));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    </td >\r\n");



WriteLiteral("    <td>\r\n\r\n        ");


            
            #line 97 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.DropDownListFor(model => item.NoiHoc_id, new SelectList(db.dmNoiHoc, "id", "tennoihoc"), item.NoiHoc_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 98 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.NoiHoc_id));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    </td>\r\n");



WriteLiteral("        <td>  \r\n        ");


            
            #line 101 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.SoQuyetDinh));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 102 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.SoQuyetDinh));

            
            #line default
            #line hidden
WriteLiteral(" \r\n    </td>\r\n");



WriteLiteral("    <td>  \r\n        ");


            
            #line 105 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.NgayCapQD));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 106 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.NgayCapQD));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </td>\r\n");



WriteLiteral("        <td> \r\n        ");


            
            #line 109 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.DropDownListFor(model => item.CheDo_id, new SelectList(db.dmCheDoHoc, "id", "tenchedohoc"), item.CheDo_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 110 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.CheDo_id));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    </td>\r\n");



WriteLiteral("    <td>\r\n        ");


            
            #line 113 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 114 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </td>\r\n");



WriteLiteral("    <td>\r\n        ");


            
            #line 117 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.ThoiGianKetThucDuKien));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 118 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.ThoiGianKetThucDuKien));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    </td>\r\n");



WriteLiteral("    <td>   \r\n        ");


            
            #line 121 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.ThoiGianKetThucChinhThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 122 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.ThoiGianKetThucChinhThuc));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    </td>\r\n");



WriteLiteral("    <td>    \r\n        ");


            
            #line 125 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.KetQua));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 126 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.KetQua));

            
            #line default
            #line hidden
WriteLiteral(" \r\n    </td>\r\n");



WriteLiteral("   <td>\r\n        ");


            
            #line 129 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.HocPhi));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 130 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.HocPhi));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    </td>\r\n");



WriteLiteral("        <td>   \r\n        ");


            
            #line 133 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.ChiPhiKhac));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 134 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.ChiPhiKhac));

            
            #line default
            #line hidden
WriteLiteral(" \r\n    </td>\r\n");



WriteLiteral("         <td> \r\n        ");


            
            #line 137 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.KinhPhiHoTro));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 138 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.KinhPhiHoTro));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </td>  \r\n");



WriteLiteral("    <td>  \r\n        ");


            
            #line 141 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.DropDownListFor(model => item.HienTrang_id, new SelectList(db.dmHienTrangDiHoc, "id", "tenhientrangdihoc"), item.HienTrang_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 142 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.HienTrang_id));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    </td>           \r\n");



WriteLiteral("    <td>  \r\n        ");


            
            #line 145 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => item.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 146 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => item.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </td>\r\n");



WriteLiteral(@"    <td>
    <input type=""submit"" style=""position:absolute; left:-999999999px"" />
    <a title=""Sửa"" id=""Edit""><span class=""ui-icon ui-icon-pencil"" style=""display:inline-block"" /></a>
    <a title=""Lưu"" id=""Save"" hidden><span class=""ui-icon ui-icon-disk"" style=""display:inline-block"" /></a>
    </td>
");


            
            #line 153 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</tr>   \r\n");


            
            #line 155 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    ViewData.TemplateInfo.HtmlFieldPrefix = null;
  }

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n    ");



            
            #line 159 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
     using (Html.BeginForm("Update_CC", "nvQTHocTap"))
    {
        ViewData.TemplateInfo.HtmlFieldPrefix = null;

            
            #line default
            #line hidden
WriteLiteral("       <td>");


            
            #line 162 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
      Write(Html.DropDownList("nvien", new SelectList(db.nvSoYeuLyLich, "nv_id", "hovaten"), string.Empty));

            
            #line default
            #line hidden
WriteLiteral(" </td>   \r\n");


            
            #line 163 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
        
            
            #line default
            #line hidden
            
            #line 163 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.HiddenFor(model => model.NV_id, new { id = "nv_id" }));

            
            #line default
            #line hidden
            
            #line 163 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                                                           

            
            #line default
            #line hidden
WriteLiteral("        <td> ");


            
            #line 164 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
        Write(Html.DropDownListFor(model => model.DonVi_id, new SelectList(db.dmDonVi, "id", "madonvi"), string.Empty, new { @class = "donvi" }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("        <td>\r\n        ");


            
            #line 166 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.DropDownListFor(model => model.LoaiChungChi_id, new SelectList(db.dmLoaiChungChi, "id", "tenloaichungchi"), string.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 167 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => model.LoaiChungChi_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("        <td>\r\n        ");


            
            #line 170 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.EditorFor(model => model.TenTruong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 171 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   Write(Html.ValidationMessageFor(model => model.TenTruong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("        <td>\r\n          ");


            
            #line 174 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
     Write(Html.EditorFor(model => model.TenKhoaHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n          ");


            
            #line 175 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
     Write(Html.ValidationMessageFor(model => model.TenKhoaHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("        <td>\r\n            ");


            
            #line 178 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.DropDownListFor(model => model.QuocGia_id, new SelectList(db.dmQuocGia, "id", "tenquocgia"), string.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 179 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.QuocGia_id));

            
            #line default
            #line hidden
WriteLiteral("        \r\n        </td>\r\n");



WriteLiteral("        <td>\r\n            ");


            
            #line 182 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.DropDownListFor(model => model.NoiHoc_id, new SelectList(db.dmNoiHoc, "id", "tennoihoc"), string.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 183 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.NoiHoc_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            ");


            
            #line 186 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.SoQuyetDinh));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 187 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.SoQuyetDinh));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("        <td>\r\n            ");


            
            #line 190 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.NgayCapQD));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 191 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.NgayCapQD));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            ");


            
            #line 194 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.DropDownListFor(model => model.CheDo_id, new SelectList(db.dmCheDoHoc, "id", "tenchedohoc"), string.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 195 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.CheDo_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("        <td>\r\n            ");


            
            #line 198 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 199 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.ThoiGianBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            ");


            
            #line 202 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.ThoiGianKetThucDuKien));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 203 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.ThoiGianKetThucDuKien));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            ");


            
            #line 206 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.ThoiGianKetThucChinhThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 207 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.ThoiGianKetThucChinhThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            ");


            
            #line 210 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.KetQua));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 211 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.KetQua));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            ");


            
            #line 214 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.HocPhi));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 215 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.HocPhi));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("          <td>\r\n            ");


            
            #line 218 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.ChiPhiKhac));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 219 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.ChiPhiKhac));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("        <td>\r\n            ");


            
            #line 222 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.KinhPhiHoTro));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 223 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.KinhPhiHoTro));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");


            
            #line 225 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       
 

            
            #line default
            #line hidden
WriteLiteral("         <td>\r\n            ");


            
            #line 228 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.DropDownListFor(model => model.HienTrang_id, new SelectList(db.dmHienTrangDiHoc, "id", "tenhientrangdihoc"), string.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 229 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.HienTrang_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");


            
            #line 231 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
        
       

            
            #line default
            #line hidden
WriteLiteral("        <td>\r\n            ");


            
            #line 234 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.EditorFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 235 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
       Write(Html.ValidationMessageFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");



WriteLiteral("         <td>\r\n            <input type=\"submit\" style=\"position:absolute; left:-9" +
"89999999px\" />\r\n            <a title=\"Lưu\" id=\"Save\"><span class=\"ui-icon ui-ico" +
"n-disk\" style=\"display:inline-block\"/></a>\r\n           ");



WriteLiteral("   \r\n       </td>      \r\n");


            
            #line 242 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
    
    }

            
            #line default
            #line hidden
WriteLiteral("    </td>\r\n    </tr>\r\n</tbody>\r\n</table>\r\n");


            
            #line 248 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
   if (Download)
  {
    
            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
Write(Html.Partial("DownloadCC", Database));

            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\nvQTHocTap\QTChungChi.cshtml"
                                         
  }

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\ninput { margin: 0 0 0 0 }\r\ninput, textarea {\r\n    border: 1px solid #e" +
"2e2e2;\r\n    background: #fff;\r\n    color: #333;\r\n    font-size: 1.2em;\r\n    marg" +
"in: 5px 0 6px 0;\r\n    padding: 1px;\r\n    width: 300px;\r\n}\r\n.hoten{ width: 160px;" +
" }\r\n.donvi { width: 160px; }\r\n.vanbang { width: 90px; }\r\n.loaitn { width: 50px; " +
"}\r\ninput, select \r\n{\r\n    width: 140px;\r\n}\r\n\r\n</style>\r\n  \t  <script type=\"text/" +
"javascript\" language=\"javascript\" src=\"/hrm/Scripts/datatables/dataTables.fixedC" +
"olumns.js\"></script>\r\n<script >\r\n    $(document).ready(function () {\r\n        va" +
"r table = $(\'#example\').DataTable({\r\n            \"sScrollY\": \"600px\",\r\n         " +
"   \"sScrollX\": \"130%\",\r\n            \"bScrollCollapse\": true,\r\n            \"bPagi" +
"nate\": false\r\n        });\r\n\r\n        new $.fn.DataTable.FixedColumns(table, {\r\n\r" +
"\n        });\r\n        var $table = $(\"#example\");\r\n        $table.find(\"[id^=ite" +
"m]\").prop(\"disabled\", true);\r\n        $table.find(\"input[type=datetime]\").datepi" +
"cker({ changeMonth: true, changeYear: true }).css(\"width\", \"80px\");\r\n        $ta" +
"ble.find(\"input,select\").css(\"border\", \"0\").css(\"border-bottom\", \"1px dotted\");\r" +
"\n        $table.find(\"input[type=datetime]\").css(\"border-bottom\", \"1px dotted\");" +
"\r\n        $(\"#Filter\").find(\"input[type=datetime]\").css(\"width\", \"80px\")\r\n      " +
"      .datepicker({ changeMonth: true, changeYear: true });\r\n        var hoten =" +
" $(\"[id$=nvien]\").combobox({\r\n            //            valueField: \'NV_id\',\r\n  " +
"          //            textField: \'HoVaTen\'\r\n        });\r\n        var donvi = $" +
"(\"[id$=DonVi_id]\").combobox({\r\n            //            valueField: \'NV_id\',\r\n " +
"           //            textField: \'HoVaTen\'\r\n        });\r\n        var nhvien =" +
" $(\"[id$=nv_id]\");\r\n        donvi.css(\"width\", \"50px\");\r\n        //  var donvi =" +
" $(\"[id$=DonVi_id]\");\r\n        //  $(\"[id$=DonVi_id]\").css(\"width\", \"50px\");\r\n  " +
"      donvi.change(function () {\r\n            hoten.trigger(\"connect\", \"/hrm/nvQ" +
"THocTap/DSNV?idDonvi=\" + $(this).val());\r\n        });\r\n        hoten.change(func" +
"tion () {\r\n            nhvien.val($(this).val());\r\n    //        alert(nhvien.va" +
"l());\r\n        });\r\n    });\r\n</script>");


        }
    }
}
#pragma warning restore 1591
