#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.HDLaoDong.Views.DanhMuc
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
    using HRM.Databases_HDLaoDong.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DanhMuc/Create_dmThoiHanHD.cshtml")]
    public partial class Create_dmThoiHanHD : System.Web.Mvc.WebViewPage<HRM.Databases_HDLaoDong.Models.dmThoiHanHD>
    {
        public Create_dmThoiHanHD()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
  
    
    var LoaiHD = new List<string>();
    LoaiHD.Add("Hợp đồng cơ hữu");
    LoaiHD.Add("Thử việc");
    LoaiHD.Add("Hợp đồng dài hạn");
    var listLoaiHD = new SelectList(LoaiHD);
    var type = new List<string>();
    type.Add("=");
    type.Add(">");
    type.Add("<");
    type.Add("KXĐ");
    var listType = new SelectList(type);


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dmThoiHanHD</legend>\r\n        <p>\r\n            Lo" +
"ại HĐ\r\n            <span onchange = \"loaiHDChange()\">\r\n            ");


            
            #line 27 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
       Write(Html.DropDownListFor(model => model.loaiHopDong, listLoaiHD, new { id = "cbxLoaiHD"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </p>\r\n        <p>\r\n            Thời hạn HĐ\r\n      " +
"      <span onchange = \"typeChange()\">\r\n            ");


            
            #line 33 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
       Write(Html.DropDownList("Type", listType));

            
            #line default
            #line hidden
WriteLiteral(@"
            </span>
            <input id = ""SoThang"" name = ""Number"" type=""number"" name=""quantity"" min=""0"" max=""100"" style = ""width:50px"" /> <span id = ""Ngay"" hidden = ""true"">Ngày</span><span id = ""Thang"">Tháng</span>
        </p>
        <p>
            <input class=""dialog"" type=""submit"" value=""Lưu"" />
        </p>
    </fieldset>
");


            
            #line 41 "..\..\Views\DanhMuc\Create_dmThoiHanHD.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"


<script>
    function loaiHDChange() {
        var elem = document.getElementById(""cbxLoaiHD""),
        selectedNode = elem.options[elem.selectedIndex];
        if (selectedNode.value == ""Thử việc"") {
            Ngay.hidden = false;
            Thang.hidden = true;
        } else {
            Thang.hidden = false;
            Ngay.hidden = true;
        }
    }
    function typeChange() {
        var elem = document.getElementById(""Type""),
        selectedNode = elem.options[elem.selectedIndex];
        if (selectedNode.value == ""KXĐ"") {
            SoThang.value = """";
            SoThang.disabled = true;
        } else {
            SoThang.disabled = false;
        }
    }
</script>
<script>
    $(""#demo"").combobox().parent().find(""input.ui-autocomplete-input"").css(""width"", ""300px"");
    $(""#Type"").combobox().parent().find(""input.ui-autocomplete-input"").css(""width"", ""235px"");
    $("".custom-combobox-input"").removeClass(""ui-state-default"");
    $("".custom-combobox-input"").removeClass(""ui-widget-content"");
    $("".custom-combobox-width"").removeClass(""ui-width-default"");
    $("".custom-combobox-input"").removeClass(""ui-corner-left"");
    $("".custom-combobox-toggle"").removeClass(""ui-state-default"");
</script>");


        }
    }
}
#pragma warning restore 1591
