#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.TTKyLuatTruoc
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TTKyLuatTruoc/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<int>
    {
        public Index()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
  
    var action = "TTKyLuatTruoc";
    ViewBag.Title = "Edit";
    var db = ViewBag.db as HRMDBEntities;
    var dt = db.SqlQuery("select * from nvTTKyLuatTruoc where NV_id=@p0", Model);
    var rand = new Random().Next();


            
            #line default
            #line hidden
WriteLiteral("\r\n<table id=\"");


            
            #line 13 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
      Write(rand);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"table table-hover table-bordered\" style=\"margin:0\">\r\n<thead>\r\n    <tr>\r\n" +
"        <th>\r\n            ");


            
            #line 17 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Editor4C("~/QLTTNhanSu/"+action+"/EditP?NV_id=" + Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>Số QĐ</th>\r\n        <th>Ngày</th>\r\n        <th>Cấp Q" +
"Đ</th>\r\n        <th>Nơi cấp</th>\r\n        <th>Lý do</th>\r\n        <th>Ghi chú</t" +
"h>\r\n        <th>Hiển thị</th>\r\n    </tr>\r\n</thead>\r\n<tbody>\r\n");


            
            #line 29 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
 foreach (DataRow dr in dt.Rows)
{

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n            ");


            
            #line 33 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Editor4U("~/QLTTNhanSu/"+action+"/EditP?id=" + dr["id"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 34 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Editor4D("~/QLTTNhanSu/"+action+"/DeleteS?id=" + dr["id"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 37 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["SoQuyetDinh"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 40 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["NgayQuyetDinh"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 43 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["CapQuyetDinh"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 46 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["NoiCapQuyetDinh"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 49 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["LyDoKyLuat"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 52 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["TrangThai"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 55 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(Html.Display(dr, dt.Columns["GhiChu"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");


            
            #line 58 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
}

            
            #line default
            #line hidden

            
            #line 59 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
 if (dt.Rows.Count == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td colspan=8 style=\"text-align:center\">\r\n            <i>Không " +
"có.</i>\r\n        </td>\r\n    </tr>\r\n");


            
            #line 66 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</tbody>\r\n</table>\r\n\r\n<script>\r\n    $(function () {\r\n        $(\"#");


            
            #line 72 "..\..\Views\TTKyLuatTruoc\Index.cshtml"
       Write(rand);

            
            #line default
            #line hidden
WriteLiteral("\").find(\"th,td\").attr(\"nowrap\", true);\r\n    });\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
