#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.QLTapSu
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\QLTapSu\Index.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\QLTapSu\Index.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\QLTapSu\Index.cshtml"
    using HRM.QLTTNhanSu.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\QLTapSu\Index.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QLTapSu/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Views\QLTapSu\Index.cshtml"
  
    ViewBag.Title = "Index";
    var db = ViewBag.db as HRMDBEntities;
    var query = "select * from dsQLTapSu ";
    query += (bool)ViewBag.All ? null : "where ThoiGianKetThuc is null";
    var dt = db.SqlQuery(query + ((bool)ViewBag.All ? " order by maDonVi, HoVaTen" : " order by ThoiGianDenHan"));
    var rand = new Random().Next();
    var no = db.SqlQuery(@"select nvQTLamViec.*, nvSoYeuLyLich.HoVaTen from nvQTLamViec
    left join dmChucDanhChuyenMon on nvQTLamViec.ChucDanhChuyenMon_id = dmChucDanhChuyenMon.id
    left join nvQLTapSu on nvQTLamViec.id = nvQLTapSu.CT_id
    left join nvSoYeuLyLich on nvQTLamViec.NV_id = nvSoYeuLyLich.NV_id
    where nvQTLamViec.ThoiGianKetThuc is null and dmChucDanhChuyenMon.qlTapSu = 1 and nvQLTapSu.id is null");


            
            #line default
            #line hidden
WriteLiteral("\r\n<p class=\"ui-state-highlight\">\r\n    Danh sách giảng viên tập sự trường ĐHDL Văn" +
" Lang\r\n    <span style=\"float:right\">\r\n        <span>Hiển thị tất cả</span>\r\n   " +
"     ");


            
            #line 23 "..\..\Views\QLTapSu\Index.cshtml"
   Write(Html.CheckBox("All"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </span>\r\n</p>\r\n\r\n");


            
            #line 27 "..\..\Views\QLTapSu\Index.cshtml"
 if (no.Rows.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <p class=\"ui-state-error\">\r\n    <span>Có ");


            
            #line 30 "..\..\Views\QLTapSu\Index.cshtml"
        Write(no.Rows.Count);

            
            #line default
            #line hidden
WriteLiteral(" giảng viên chưa quản lý tập sự: </span>\r\n");


            
            #line 31 "..\..\Views\QLTapSu\Index.cshtml"
     foreach (DataRow nr in no.Rows)
    {

            
            #line default
            #line hidden
WriteLiteral("        <span>");


            
            #line 33 "..\..\Views\QLTapSu\Index.cshtml"
         Write(Html.ActionLink(nr["HoVaTen"] as string, "Details", "HSNhanSu", new { id = nr["NV_id"], tab = "QTLamViec" }, new { target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral(" </span>\r\n");


            
            #line 34 "..\..\Views\QLTapSu\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    </p>\r\n");


            
            #line 36 "..\..\Views\QLTapSu\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<table id=\"");


            
            #line 38 "..\..\Views\QLTapSu\Index.cshtml"
      Write(rand);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""table table-bordered table-hover"">
<thead class=""ui-widget-header"">
    <tr>
        <th nowrap>Họ và tên</th>
        <th nowrap>Đơn vị</th>
        <th style=""text-align:center"" nowrap>Thời gian<br />tuyển dụng</th>
        <th style=""text-align:center"" nowrap data-tip=""Chức danh chuyên môn"">CD<br />CM</th>
        <th style=""text-align:center"" nowrap>Thời gian<br />bắt đầu</th>
        <th style=""text-align:center"" nowrap>Thời gian<br />đến hạn</th>
        <th style=""text-align:center"" nowrap>Thời gian<br />kết thúc</th>
        <th style=""text-align:center"" nowrap data-tip=""Tháng làm việc"">T</th>
        <th style=""text-align:center"" nowrap>Ngày<br />thông báo</th>
        <th style=""text-align:center"" nowrap>Ngày nhận<br />hồ sơ</th>
        <th style=""text-align:center"" nowrap>Ngày lập<br />tờ trình</th>
        <!--
        <th title=""Bồi dưỡng nghiệp vụ sư phạm"" nowrap>BDNVSP</th>
        <th title=""Lý luận dạy học đại học"" nowrap>LLDHĐH</th>
        -->
        <th nowrap></th>
    </tr>
</thead>
<tbody class=""ui-widget-content"">
");


            
            #line 60 "..\..\Views\QLTapSu\Index.cshtml"
 foreach (DataRow dr in dt.Rows)
{

            
            #line default
            #line hidden
WriteLiteral("    <tr id=\"");


            
            #line 62 "..\..\Views\QLTapSu\Index.cshtml"
       Write(dr["NV_id"]);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <td>\r\n            ");


            
            #line 64 "..\..\Views\QLTapSu\Index.cshtml"
       Write(Html.ActionLink(dr["HoVaTen"] as string, "Details", "HSNhanSu", new { id = dr["NV_id"], tab = "QTLamViec" }, new { target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            <mark data-tip=\"");


            
            #line 67 "..\..\Views\QLTapSu\Index.cshtml"
                       Write(dr["tenDonVi"]);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 67 "..\..\Views\QLTapSu\Index.cshtml"
                                        Write(dr["maDonVi"]);

            
            #line default
            #line hidden
WriteLiteral("</mark>\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 70 "..\..\Views\QLTapSu\Index.cshtml"
        Write(dr["NgayTuyenDung"] is DBNull ? null : (dr["NgayTuyenDung"] as DateTime?).Value.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            <mark data-tip=\"");


            
            #line 73 "..\..\Views\QLTapSu\Index.cshtml"
                       Write(dr["tenChucDanhChuyenMon"]);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 73 "..\..\Views\QLTapSu\Index.cshtml"
                                                    Write(dr["maChucDanhChuyenMon"]);

            
            #line default
            #line hidden
WriteLiteral("</mark>\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 76 "..\..\Views\QLTapSu\Index.cshtml"
        Write(((DateTime)dr["ThoiGianBatDau"]).ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            <b>");


            
            #line 79 "..\..\Views\QLTapSu\Index.cshtml"
           Write(dr["ThoiGianDenHan"] is DBNull ? null : (dr["ThoiGianDenHan"] as DateTime?).Value.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n        </td>\r\n        <td>\r\n            <b>");


            
            #line 82 "..\..\Views\QLTapSu\Index.cshtml"
           Write(dr["ThoiGianKetThuc"] is DBNull ? null : (dr["ThoiGianKetThuc"] as DateTime?).Value.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n        </td>\r\n        <td>\r\n");


            
            #line 85 "..\..\Views\QLTapSu\Index.cshtml"
           var ThoiGianBatDau = (DateTime)dr["ThoiGianBatDau"]; var ThoiGianKetThuc = dr["ThoiGianKetThuc"] as DateTime?; 

            
            #line default
            #line hidden
WriteLiteral("            <mark><sup data-tip=\"");


            
            #line 86 "..\..\Views\QLTapSu\Index.cshtml"
                            Write(TinhThamNien.Ti1nh(ThoiGianBatDau, ThoiGianKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 86 "..\..\Views\QLTapSu\Index.cshtml"
                                                                                   Write(ThoiGianKetThuc.HasValue ? (int)((ThoiGianKetThuc.Value - ThoiGianBatDau).Days / (365.25 / 12) + 0.5) : (int)((DateTime.Now - ThoiGianBatDau).Days / (365.25 / 12) + 0.5));

            
            #line default
            #line hidden
WriteLiteral("</sup></mark>\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 89 "..\..\Views\QLTapSu\Index.cshtml"
       Write(dr["NgayThongBao"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 92 "..\..\Views\QLTapSu\Index.cshtml"
       Write(dr["NgayNhanHoSo"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");


            
            #line 95 "..\..\Views\QLTapSu\Index.cshtml"
       Write(dr["NgayLapToTrinh"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            <button class=\"select\" style=\"width:16" +
"px\"></button>\r\n            <ul style=\"z-index:1000\">\r\n                <li>");


            
            #line 100 "..\..\Views\QLTapSu\Index.cshtml"
               Write(Html.Link4U("~/QLTTNhanSu/QLTapSu/EditP?id=" + dr["id"], "Edit"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                <li>");


            
            #line 101 "..\..\Views\QLTapSu\Index.cshtml"
               Write(Html.Link4D("~/QLTTNhanSu/QLTapSu/DeleteS?id=" + dr["id"], "Delete"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            </ul>\r\n        </td>\r\n    </tr>\r\n");


            
            #line 105 "..\..\Views\QLTapSu\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</tbody>\r\n</table>\r\n\r\n<script>\r\n    $(function () {\r\n        $(\"#");


            
            #line 111 "..\..\Views\QLTapSu\Index.cshtml"
       Write(rand);

            
            #line default
            #line hidden
WriteLiteral("\").find(\"th\").attr(\"nowrap\", true);\r\n        $(\"#");


            
            #line 112 "..\..\Views\QLTapSu\Index.cshtml"
       Write(rand);

            
            #line default
            #line hidden
WriteLiteral(@""").find("".select"").button({
            text: false,
            icons: { primary: ""ui-icon-circle-triangle-s"" }
        }).click(function () {
            var menu = $(this).next().show().position({
                my: ""left top"",
                at: ""left bottom"",
                of: this
            });
            $(document).one(""click"", function () { menu.hide(); });
            return false;
        }).next().hide().menu();
        $(""input#All"").click(function () {
            window.location = """);


            
            #line 125 "..\..\Views\QLTapSu\Index.cshtml"
                          Write(Url.Action("Index", "QLTapSu"));

            
            #line default
            #line hidden
WriteLiteral("?All=\" + this.checked;\r\n        });\r\n    });\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
