#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.QuaTrinhHoc
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QuaTrinhHoc/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<HRM.Databases.Models.QuaTrinhHoc>
    {
        public Details()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\QuaTrinhHoc\Details.cshtml"
  
    ViewBag.Title = "Details";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Details</h2>\r\n\r\n<fieldset>\r\n    <legend>QuaTrinhHoc</legend>\r\n\r\n    <div cl" +
"ass=\"display-label\">\r\n         ");


            
            #line 13 "..\..\Views\QuaTrinhHoc\Details.cshtml"
    Write(Html.DisplayNameFor(model => model.NV_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 16 "..\..\Views\QuaTrinhHoc\Details.cshtml"
   Write(Html.DisplayFor(model => model.NV_id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div class=\"display-label\">\r\n         ");


            
            #line 20 "..\..\Views\QuaTrinhHoc\Details.cshtml"
    Write(Html.DisplayNameFor(model => model.BacHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 23 "..\..\Views\QuaTrinhHoc\Details.cshtml"
   Write(Html.DisplayFor(model => model.BacHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n     <div class=\"display-label\">\r\n         ");


            
            #line 26 "..\..\Views\QuaTrinhHoc\Details.cshtml"
    Write(Html.DisplayNameFor(model => model.TruongHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 29 "..\..\Views\QuaTrinhHoc\Details.cshtml"
   Write(Html.DisplayFor(model => model.TruongHoc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div class=\"display-label\">\r\n         ");


            
            #line 33 "..\..\Views\QuaTrinhHoc\Details.cshtml"
    Write(Html.DisplayNameFor(model => model.NamBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 36 "..\..\Views\QuaTrinhHoc\Details.cshtml"
   Write(Html.DisplayFor(model => model.NamBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div class=\"display-label\">\r\n         ");


            
            #line 40 "..\..\Views\QuaTrinhHoc\Details.cshtml"
    Write(Html.DisplayNameFor(model => model.NamKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 43 "..\..\Views\QuaTrinhHoc\Details.cshtml"
   Write(Html.DisplayFor(model => model.NamKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div class=\"display-label\">\r\n         ");


            
            #line 47 "..\..\Views\QuaTrinhHoc\Details.cshtml"
    Write(Html.DisplayNameFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 50 "..\..\Views\QuaTrinhHoc\Details.cshtml"
   Write(Html.DisplayFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</fieldset>\r\n<p>\r\n    ");


            
            #line 54 "..\..\Views\QuaTrinhHoc\Details.cshtml"
Write(Html.ActionLink("Edit", "Edit", new { id=Model.id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n    ");


            
            #line 55 "..\..\Views\QuaTrinhHoc\Details.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
