#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLTTNhanSu.Views.QHGiaDinh
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\QHGiaDinh\Edit.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\QHGiaDinh\Edit.cshtml"
    using HRM.Databases.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\QHGiaDinh\Edit.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QHGiaDinh/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<int?>
    {
        public Edit()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Views\QHGiaDinh\Edit.cshtml"
  
    var action = "QHGiaDinh";
    var NV_id = ViewBag.NV_id as int?;
    var db = ViewBag.db as HRMDBEntities;
    var dt = db.SqlQuery("select * from nvQHGiaDinh where id=@p0", Model.HasValue ? Model.Value : 0);
    var dr = dt.Rows.Count > 0 ? dt.Rows[0] : null;

    var QuanHe = "QuanHe_id";
    
    var rand = new Random().Next();


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 17 "..\..\Views\QHGiaDinh\Edit.cshtml"
 using (Html.BeginForm(Model.HasValue ? "UpdateS" : "CreateS", action))
{
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\QHGiaDinh\Edit.cshtml"
Write(Html.Hidden("id", Model));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\QHGiaDinh\Edit.cshtml"
                             
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\QHGiaDinh\Edit.cshtml"
Write(Html.Hidden("NV_id", NV_id.HasValue ? NV_id.Value : dr["NV_id"]));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\QHGiaDinh\Edit.cshtml"
                                                                     

            
            #line default
            #line hidden
WriteLiteral("<dl id=\"");


            
            #line 21 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(rand);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"dl-horizontal\">\r\n    <dt>Mối quan hệ</dt>\r\n    <dd>");


            
            #line 23 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.DropDownList(QuanHe, new SelectList(db.dmMoiQuanHe, "id", "tenMoiQuanHe", dr != null ? dr[QuanHe] : null), String.Empty));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Họ và tên</dt>\r\n    <dd>");


            
            #line 25 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.Editor(dr, dt.Columns["HoTen"]));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Năm sinh</dt>\r\n    <dd>");


            
            #line 27 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.Editor(dr, dt.Columns["NgaySinh"]));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Nghề nghiệp</dt>\r\n    <dd>");


            
            #line 29 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.Editor(dr, dt.Columns["NgheNghiep"]));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Nơi công tác</dt>\r\n    <dd>");


            
            #line 31 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.Editor(dr, dt.Columns["CoQuan"]));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Nơi cư trú</dt>\r\n    <dd>");


            
            #line 33 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.Editor(dr, dt.Columns["DiaChi"]));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Mã số</dt>\r\n    <dd>");


            
            #line 35 "..\..\Views\QHGiaDinh\Edit.cshtml"
   Write(Html.Editor(dr, dt.Columns["MaSoThue"]));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt></dt>\r\n    <dd>\r\n        <input type=\"submit\" value=\"Save\" />\r\n   " +
"     <a title=\"Close\" class=\"close\" href=\"\">X</a>\r\n    </dd>\r\n</dl>\r\n");


            
            #line 42 "..\..\Views\QHGiaDinh\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var form = $(\"#");


            
            #line 45 "..\..\Views\QHGiaDinh\Edit.cshtml"
              Write(rand);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n    form.find(\"[type=date]\").datepicker({\r\n        changeMonth: true,\r\n     " +
"   changeYear: true,\r\n        dateFormat: \"dd/mm/yy\"\r\n    }).prop(\"type\", \"text\"" +
");\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
