#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.TaiNguyen
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\TaiNguyen\Create.cshtml"
    using HRM.QLDanhMuc.Models;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\TaiNguyen\Create.cshtml"
    using HRM.Webpages.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TaiNguyen/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<HRM.Databases.Models.TaiNguyen>
    {
        public Create()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\TaiNguyen\Create.cshtml"
  
    ViewBag.Title = "Create";


            
            #line default
            #line hidden

            
            #line 7 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.BeginDiv());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Create</h2>\r\n\r\n");


            
            #line 11 "..\..\Views\TaiNguyen\Create.cshtml"
 using (Html.BeginForm("Create", "TaiNguyen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\TaiNguyen\Create.cshtml"
                             
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.HiddenFor(model => model.idTaiNguyen));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\TaiNguyen\Create.cshtml"
                                               


            
            #line default
            #line hidden
WriteLiteral("    <p><span class=\"ui-icon ui-icon-home\" style=\"display:inline-block\" ></span>");


            
            #line 16 "..\..\Views\TaiNguyen\Create.cshtml"
                                                                          Write(Model.getFolder());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 17 "..\..\Views\TaiNguyen\Create.cshtml"

    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.LabelForVN(model => model.tenTaiNguyen));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\TaiNguyen\Create.cshtml"
                                                 
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.EditorFor(model => model.tenTaiNguyen));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\TaiNguyen\Create.cshtml"
                                                
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.ValidationMessageFor(model => model.tenTaiNguyen));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\TaiNguyen\Create.cshtml"
                                                           

    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.HiddenFor(model => model.laThuMuc));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\TaiNguyen\Create.cshtml"
                                            
    if (Model.laThuMuc == false)
    {
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\TaiNguyen\Create.cshtml"
   Write(Html.LabelForVN(model => model.tepDinhKem));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\TaiNguyen\Create.cshtml"
                                                   
        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\TaiNguyen\Create.cshtml"
   Write(Html.TextBoxFor(model => model.tepDinhKem, new { type = "file" }));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\TaiNguyen\Create.cshtml"
                                                                          
        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\TaiNguyen\Create.cshtml"
   Write(Html.ValidationMessageFor(model => model.tepDinhKem));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\TaiNguyen\Create.cshtml"
                                                             
    }


            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    <input type=\"submit\" value=\"Create\" />\r\n</p>\r\n");


            
            #line 33 "..\..\Views\TaiNguyen\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n    ");


            
            #line 36 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.ActionLink("Back to List", "Index", new { parent = Model.idTaiNguyen }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");


            
            #line 39 "..\..\Views\TaiNguyen\Create.cshtml"
Write(Html.EndDiv());

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
