#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLDanhMuc.Views.QuanHuyen
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/QuanHuyen/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.Databases.Models.dmQuanHuyen>
    {
        public Edit()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\QuanHuyen\Edit.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\QuanHuyen\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\QuanHuyen\Edit.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dmQuanHuyen</legend>\r\n\r\n        ");


            
            #line 9 "..\..\Views\QuanHuyen\Edit.cshtml"
   Write(Html.HiddenFor(model => model.id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 12 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.LabelFor(model => model.maQuanHuyen));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 15 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.EditorFor(model => model.maQuanHuyen));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 16 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.maQuanHuyen));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 20 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.LabelFor(model => model.tenQuanHuyen));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 23 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.EditorFor(model => model.tenQuanHuyen));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 24 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.tenQuanHuyen));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 27 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.LabelFor(model => model.idTinhThanh, "tên tỉnh/thành"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n        ");



WriteLiteral("\r\n         ");


            
            #line 32 "..\..\Views\QuanHuyen\Edit.cshtml"
    Write(Html.DropDownList("idTinhThanh", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 33 "..\..\Views\QuanHuyen\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.idTinhThanh));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <p>\r\n            <input class=\"dialog\" type=\"submit\" " +
"value=\"Save\" />\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 40 "..\..\Views\QuanHuyen\Edit.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
