#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.QLBHXH.Views.dmMucLuongToiThieuVung
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/dmMucLuongToiThieuVung/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<HRM.QLBHXH.Models.dmMucLuongToiThieuVung>
    {
        public Edit()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
  
    ViewBag.Title = "Edit";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>\r\n    Chỉnh sửa</h2>\r\n");

            
            #line 7 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>dmMucLuongToiThieuVung</legend>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
   Write(Html.HiddenFor(model => model.id));

            
            #line default
            #line hidden
WriteLiteral("\r\n         <b> Ngày bắt đầu</b>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.TextBoxFor(model => model.NgayBatDau, new { style = "width: 100px", @id = "NgayBatDau1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.NgayBatDau));

            
            #line default
            #line hidden
WriteLiteral("\r\n      \r\n       \r\n           <b>Ngày kết thúc</b>\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.TextBoxFor(model => model.NgayKetThuc, new { style = "width: 100px", @id = "NgayKetThuc1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.NgayKetThuc));

            
            #line default
            #line hidden
WriteLiteral("\r\n      \r\n        \r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n              <b>Mức lương tối thiểu vùng (VNĐ)  </b>\r\n        <input");

WriteLiteral(" id=\"MucLuongTTV1\"");

WriteLiteral("  value=");

WriteLiteral(" ");

            
            #line 26 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
                                    Write(String.Format("{0:#,##0}", Model.MucLuong));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.HiddenFor(model => model.MucLuong, new { @id = "MucLuong1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.MucLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n                   <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n            <b>Mức lương tối thiểu vùng tc(VNĐ)  </b>\r\n \r\n");

            
            #line 37 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
         if (Model.MucLuongCaoHonTrungCap != null)
        {

            
            #line default
            #line hidden
WriteLiteral("           <input");

WriteLiteral(" id=\"MucLuongTTV_CaoHonTC1\"");

WriteAttribute("value", Tuple.Create(" value=", 1353), Tuple.Create("", 1417)
            
            #line 39 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1360), Tuple.Create<System.Object, System.Int32>(String.Format("{0:#,##0}", Model.MucLuongCaoHonTrungCap)
            
            #line default
            #line hidden
, 1360), false)
);

WriteLiteral(" />");

            
            #line 39 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
                                                                                                               }
        else
        {
            
            #line default
            #line hidden
WriteLiteral(" <input");

WriteLiteral(" id=\"MucLuongTTV_CaoHonTC1\"");

WriteLiteral(" value=\"\"");

WriteLiteral(") />");

            
            #line 41 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
                                                        }

            
            #line default
            #line hidden
WriteLiteral("          </div>\r\n            <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.HiddenFor(model => model.MucLuongCaoHonTrungCap, new { @id = "MucLuongCaoHonTrungCap1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.MucLuong));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    \r\n    \r\n       \r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n           <b> Thuộc vùng</b> \r\n     \r\n");

WriteLiteral("            ");

            
            #line 53 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.EditorFor(model => model.ThuocVung));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 54 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.ThuocVung));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n            <b> Đang áp dụng</b> \r\n      \r\n");

WriteLiteral("            ");

            
            #line 59 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.EditorFor(model => model.TrangThai));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 60 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.TrangThai));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n           <b> Ghi chú</b> \r\n       \r\n");

WriteLiteral("            ");

            
            #line 65 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.EditorFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 66 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.GhiChu));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <p>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Lưu\"");

WriteLiteral(" />\r\n        </p>\r\n    </fieldset>\r\n");

            
            #line 72 "..\..\Views\dmMucLuongToiThieuVung\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n$(\"#NgayBatDau1\").datepicker({\r\n        changeDay: true,\r\n       chan" +
"geMonth: true,\r\n        changeYear: true,\r\n    });\r\n    $(\"#NgayKetThuc1\").datep" +
"icker({\r\n        changeDay: true,\r\n       changeMonth: true,\r\n        changeYear" +
": true,\r\n    });\r\n\r\n//tu them dau phay vao so\r\n$(\'#MucLuongTTV1\').keyup(function" +
"(event) {\r\n\r\n  // skip for arrow keys\r\n  if(event.which >= 37 && event.which <= " +
"40){\r\n    event.preventDefault();\r\n  }\r\n\r\n  $(this).val(function(index, value) {" +
"\r\n    return value\r\n      .replace(/\\D/g, \"\")\r\n      .replace(/\\B(?=(\\d{3})+(?!\\" +
"d))/g, \".\")\r\n    ;\r\n  });\r\n\r\n\r\n\r\n\r\n});\r\n$(\'#MucLuongTTV_CaoHonTC1\').keyup(functi" +
"on(event) {\r\n\r\n  // skip for arrow keys\r\n  if(event.which >= 37 && event.which <" +
"= 40){\r\n    event.preventDefault();\r\n  }\r\n\r\n  $(this).val(function(index, value)" +
" {\r\n    return value\r\n      .replace(/\\D/g, \"\")\r\n      .replace(/\\B(?=(\\d{3})+(?" +
"!\\d))/g, \".\")\r\n    ;\r\n  });\r\n});\r\n\r\n\r\n    $(\"#MucLuongTTV1\").keyup(function () {" +
"\r\n\r\n            //Clear the hidden field\r\n            $(\"#MucLuong1\").val(\"\");\r\n" +
"\r\n            //Create char array from phone number field\r\n            var charA" +
"rray = $(this).val().split(\"\");\r\n\r\n            var phoneNumber = \"\";\r\n\r\n        " +
"    //Iterate over each character in the char array\r\n            //and determine" +
" if it is a number\r\n            $.each(charArray, function (index, value) {\r\n   " +
"             if (!isNaN(value) && value != \" \") {\r\n                    phoneNumb" +
"er = phoneNumber + value;\r\n                }\r\n            });\r\n\r\n            //S" +
"et hidden field\r\n            $(\"#MucLuong1\").val(phoneNumber);\r\n  $(\"#MucLuongCa" +
"oHonTrungCap1\").val(parseInt(phoneNumber)+parseInt(Math.round(phoneNumber*0.07))" +
");\r\n        //tu them dau phay vao so\r\n\r\n\r\n    \r\n         var value =parseInt(ph" +
"oneNumber)+parseInt(Math.round(phoneNumber*0.07)) // i.e. some decimal number\r\n\r" +
"\nvar num2 = value.toString().split(\'.\');\r\nvar thousands = num2[0].split(\'\').reve" +
"rse().join(\'\').match(/.{1,3}/g).join(\'.\');\r\nvar decimals = (num2[1]) ? \'.\'+num2[" +
"1] : \'\';\r\n\r\nvar answer =  thousands.split(\'\').reverse().join(\'\')+decimals;  \r\n  " +
"         \r\n                $(\"#MucLuongTTV_CaoHonTC1\").val(answer);\r\n\r\n\r\n       " +
"      \r\n\r\n            \r\n        });\r\n\r\n        \r\n    $(\"#MucLuongTTV_CaoHonTC1\")" +
".keyup(function () {\r\n\r\n            //Clear the hidden field\r\n            $(\"#Mu" +
"cLuongCaoHonTrungCap1\").val(\"\");\r\n//             $(\"#MucLuongTTV_CaoHonTC\").val(" +
"\"\");\r\n            \r\n\r\n            //Create char array from phone number field\r\n " +
"           var charArray = $(this).val().split(\"\");\r\n\r\n            var phoneNumb" +
"er1 = \"\";\r\n\r\n            //Iterate over each character in the char array\r\n      " +
"      //and determine if it is a number\r\n            $.each(charArray, function " +
"(index, value) {\r\n                if (!isNaN(value) && value != \" \") {\r\n        " +
"            phoneNumber1 = phoneNumber1 + value;\r\n                }\r\n           " +
" });\r\n\r\n            //Set hidden field\r\n           \r\n        $(\"#MucLuongCaoHonT" +
"rungCap1\").val(phoneNumber1);\r\n\r\n\r\n            \r\n        });\r\n\r\n\r\n\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
